const PHRASE_DATA = {
  "order": {
    "0": "phrase-day",
    "1": "phrase-family",
    "2": "phrase-food",
    "3": "phrase-animals",
    "4": "phrase-weather",
    "5": "phrase-emotions",
    "6": "phrase-prepositions",
    "7": "phrase-travel",
    "8": "phrase-adverbs",
    "9": "phrase-agreement",
    "10": "phrase-reactions",
    "11": "phrase-support",
    "12": "phrase-everyday",
    "13": "phrase-appraisal",
    "14": "phrase-tenses",
    "15": "phrase-pro",
    "16": "phrase-polite",
    "17": "phrase-replies",
    "18": "phrase-advanced",
    "19": "phrase-units",
    "20": "phrase-degree"
  },
  "categories": {
    "phrase-day": {
      "title": "Мій день — My Day",
      "phrases": [
        { "en": "I get up and wash my face.", "uk": "Я встаю і мию обличчя." },
        { "en": "I eat breakfast and drink milk.", "uk": "Я їм сніданок і п'ю молоко." },
        { "en": "I go to school with my friend.", "uk": "Я йду до школи з другом." },
        { "en": "I read and write at school.", "uk": "Я читаю і пишу у школі." },
        { "en": "I play and run in the park.", "uk": "Я граю і бігаю в парку." },
        { "en": "In the evening I cook dinner.", "uk": "Увечері я готую вечерю." },
        { "en": "At night I sleep in my bed.", "uk": "Уночі я сплю у своєму ліжку." }
      ]
    },
    "phrase-family": {
      "title": "Моя сім'я — My Family",
      "phrases": [
        { "en": "I love my mother and father.", "uk": "Я люблю маму і тата." },
        { "en": "My sister is happy today.", "uk": "Моя сестра сьогодні щаслива." },
        { "en": "My brother plays with the dog.", "uk": "Мій брат грає з собакою." },
        { "en": "Grandmother cooks tasty food.", "uk": "Бабуся готує смачну їжу." },
        { "en": "Grandfather reads a book.", "uk": "Дідусь читає книгу." },
        { "en": "We are a big family.", "uk": "Ми велика сім'я." },
        { "en": "I hug my baby brother.", "uk": "Я обіймаю свого братика." }
      ]
    },
    "phrase-food": {
      "title": "Їжа та напої — Food and Drinks",
      "phrases": [
        { "en": "I am hungry and want to eat.", "uk": "Я голодний і хочу їсти." },
        { "en": "I like apples and bananas.", "uk": "Мені подобаються яблука і банани." },
        { "en": "Mother makes soup in the kitchen.", "uk": "Мама готує суп на кухні." },
        { "en": "I drink water and juice.", "uk": "Я п'ю воду і сік." },
        { "en": "The bread is fresh and warm.", "uk": "Хліб свіжий і теплий." },
        { "en": "We eat fish and rice for dinner.", "uk": "Ми їмо рибу і рис на вечерю." },
        { "en": "I love sweet cake and tea.", "uk": "Я люблю солодкий торт і чай." }
      ]
    },
    "phrase-animals": {
      "title": "Тварини — Animals",
      "phrases": [
        { "en": "The cat sleeps on the chair.", "uk": "Кіт спить на стільці." },
        { "en": "The dog runs in the garden.", "uk": "Собака бігає в саду." },
        { "en": "A bird sings in the tree.", "uk": "Пташка співає на дереві." },
        { "en": "The cow and horse live on a farm.", "uk": "Корова і кінь живуть на фермі." },
        { "en": "Fish swim in the river.", "uk": "Риби плавають у річці." },
        { "en": "The lion is big and strong.", "uk": "Лев великий і сильний." },
        { "en": "I see a small rabbit.", "uk": "Я бачу маленького кролика." }
      ]
    },
    "phrase-weather": {
      "title": "Погода та пори року — Weather and Seasons",
      "phrases": [
        { "en": "Today the sun is warm.", "uk": "Сьогодні сонце тепле." },
        { "en": "In winter we play with snow.", "uk": "Взимку ми граємо зі снігом." },
        { "en": "In spring the flowers grow.", "uk": "Навесні ростуть квіти." },
        { "en": "In summer we swim in the sea.", "uk": "Влітку ми плаваємо в морі." },
        { "en": "In autumn the wind is cold.", "uk": "Восени вітер холодний." },
        { "en": "It is raining, take an umbrella.", "uk": "Йде дощ, візьми парасольку." },
        { "en": "I like a sunny day.", "uk": "Мені подобається сонячний день." }
      ]
    },
    "phrase-emotions": {
      "title": "Емоції — Emotions",
      "phrases": [
        { "en": "I feel overwhelmed when I have too much work.", "uk": "Я почуваюся приголомшеним, коли маю забагато роботи." },
        { "en": "She was relieved when the exam was over.", "uk": "Вона відчула полегшення, коли іспит закінчився." },
        { "en": "He felt guilty for forgetting her birthday.", "uk": "Він почувався винним за те, що забув про її день народження." },
        { "en": "I am grateful for your help.", "uk": "Я вдячний за вашу допомогу." },
        { "en": "She was embarrassed when she fell in public.", "uk": "Вона збентежилася, коли впала на людях." },
        { "en": "He is confident about his skills.", "uk": "Він впевнений у своїх навичках." },
        { "en": "We are all enthusiastic about the new project.", "uk": "Ми всі сповнені ентузіазму щодо нового проєкту." },
        { "en": "She feels content with her life.", "uk": "Вона задоволена своїм життям." }
      ]
    },
    "phrase-prepositions": {
      "title": "Прийменники — Prepositions",
      "phrases": [
        { "en": "Despite the rain, we went for a walk.", "uk": "Незважаючи на дощ, ми пішли на прогулянку." },
        { "en": "Throughout the year she studied hard.", "uk": "Протягом року вона наполегливо навчалася." },
        { "en": "He walked towards the door.", "uk": "Він пішов у напрямку до дверей." },
        { "en": "This is beyond my understanding.", "uk": "Це за межами мого розуміння." },
        { "en": "The cat hid beneath the table.", "uk": "Кіт сховався під столом." },
        { "en": "She stood among her friends.", "uk": "Вона стояла серед своїх друзів." },
        { "en": "Please stay within the marked area.", "uk": "Будь ласка, залишайтеся в межах позначеної зони." },
        { "en": "Unlike her sister, she loves sports.", "uk": "На відміну від сестри, вона любить спорт." }
      ]
    },
    "phrase-travel": {
      "title": "Подорож та відпочинок — Travel and Vacation",
      "phrases": [
        { "en": "The beach was peaceful and warm.", "uk": "Пляж був спокійним і теплим." },
        { "en": "The trip was exciting and memorable.", "uk": "Поїздка була захопливою і незабутньою." },
        { "en": "The hotel room was comfortable and clean.", "uk": "Номер у готелі був комфортним і чистим." },
        { "en": "The city is amazing — there is so much to see.", "uk": "Місто дивовижне — тут так багато всього побачити." },
        { "en": "We had an enjoyable evening at the restaurant.", "uk": "Ми провели приємний вечір у ресторані." },
        { "en": "The mountain air was refreshing and cool.", "uk": "Гірське повітря було освіжаючим і прохолодним." },
        { "en": "It is safe to travel alone here.", "uk": "Тут безпечно подорожувати наодинці." },
        { "en": "We had so much fun on the trip.", "uk": "Ми так гарно провели час у подорожі." }
      ]
    },
    "phrase-adverbs": {
      "title": "Прислівники — Adverbs",
      "phrases": [
        { "en": "I was tired. Nevertheless, I finished the work.", "uk": "Я втомився. Тим не менш, я закінчив роботу." },
        { "en": "She gradually learned to speak English well.", "uk": "Вона поступово навчилася добре говорити англійською." },
        { "en": "He barely had time to catch the train.", "uk": "Він ледве встиг на потяг." },
        { "en": "The two things happened simultaneously.", "uk": "Дві речі сталися одночасно." },
        { "en": "He undoubtedly made the right decision.", "uk": "Він безсумнівно прийняв правильне рішення." },
        { "en": "She reluctantly agreed to help.", "uk": "Вона неохоче погодилася допомогти." },
        { "en": "He consistently gets good results at school.", "uk": "Він послідовно отримує хороші результати у школі." },
        { "en": "The report was thoroughly checked before sending.", "uk": "Звіт був ретельно перевірений перед відправленням." }
      ]
    },
    "phrase-agreement": {
      "title": "Згода та розуміння — Agreement",
      "phrases": [
        { "en": "Fair enough.", "uk": "Справедливо." },
        { "en": "That makes sense.", "uk": "Логічно." },
        { "en": "I'm with you.", "uk": "Я з тобою згоден." },
        { "en": "Good point.", "uk": "Гарне зауваження." },
        { "en": "I hear you.", "uk": "Я тебе розумію." },
        { "en": "Exactly!", "uk": "Саме так." },
        { "en": "You got it.", "uk": "Саме так / Домовились." },
        { "en": "That's fair.", "uk": "Це чесно." },
        { "en": "Works for me.", "uk": "Мене влаштовує." },
        { "en": "You bet.", "uk": "Авжеж." },
        { "en": "Sounds good!", "uk": "Звучить добре! / Домовилися!" },
        { "en": "That's a good point.", "uk": "Це слушна думка." },
        { "en": "I don't mind.", "uk": "Я не проти." },
        { "en": "You've got a point.", "uk": "У ваших словах є сенс." },
        { "en": "I couldn't agree more.", "uk": "Повністю погоджуюся." },
        { "en": "It's worth it.", "uk": "Це того варте." },
        { "en": "Never mind.", "uk": "Неважливо. / Забудьте." },
        { "en": "That's enough.", "uk": "Цього достатньо." }
      ]
    },
    "phrase-reactions": {
      "title": "Короткі реакції — Quick Reactions",
      "phrases": [
        { "en": "No kidding!", "uk": "Та ну!" },
        { "en": "No way!", "uk": "Та ну!" },
        { "en": "You wish.", "uk": "Ага, мрій." },
        { "en": "Not a chance.", "uk": "Навіть не думай." },
        { "en": "Here we go.", "uk": "Ну, почалося." },
        { "en": "There you go.", "uk": "Ось бачиш / Тримай." },
        { "en": "That figures.", "uk": "Цього й варто було чекати." },
        { "en": "Tell me about it!", "uk": "Та не кажи!" },
        { "en": "Don't get me started.", "uk": "Навіть не починай." },
        { "en": "It rings a bell.", "uk": "Звучить знайомо." },
        { "en": "What do you mean?", "uk": "Що ви маєте на увазі?" },
        { "en": "What a pity!", "uk": "Як шкода!" },
        { "en": "I didn't catch that.", "uk": "Я не розчув / не розчула." },
        { "en": "Could you repeat that?", "uk": "Можете повторити?" },
        { "en": "How come?", "uk": "Як так? / Чому?" },
        { "en": "What's the matter?", "uk": "Що сталося?" },
        { "en": "Don't get me wrong.", "uk": "Не зрозумійте мене неправильно." },
        { "en": "That's not fair.", "uk": "Це несправедливо." },
        { "en": "I'm kidding!", "uk": "Я жартую!" },
        { "en": "That's a relief!", "uk": "Яке полегшення!" }
      ]
    },
    "phrase-support": {
      "title": "Підтримка та вибір — Support and Choice",
      "phrases": [
        { "en": "I'm in.", "uk": "Я в справі." },
        { "en": "Count me in.", "uk": "Розраховуй на мене." },
        { "en": "I'm on it.", "uk": "Уже займаюся." },
        { "en": "You got this!", "uk": "У тебе вийде." },
        { "en": "Suit yourself.", "uk": "Як знаєш." },
        { "en": "Be my guest.", "uk": "Будь ласка, не соромся." },
        { "en": "It's up to you.", "uk": "Вирішуй сам." },
        { "en": "You do you.", "uk": "Роби так, як вважаєш за потрібне." },
        { "en": "Give it a shot.", "uk": "Спробуй." },
        { "en": "Fingers crossed!", "uk": "Тримаймо кулаки." },
        { "en": "Let me think.", "uk": "Дайте мені подумати." },
        { "en": "I'm not sure.", "uk": "Я не впевнений / не впевнена." },
        { "en": "It depends.", "uk": "Це залежить від обставин." },
        { "en": "I have no idea.", "uk": "Я не маю уявлення." },
        { "en": "I'll think about it.", "uk": "Я про це подумаю." },
        { "en": "Let's figure it out.", "uk": "Давайте розберемося." },
        { "en": "You never know.", "uk": "Ніколи не знаєш." },
        { "en": "It's up to me.", "uk": "Це залежить від мене." }
      ]
    },
    "phrase-everyday": {
      "title": "Побутове спілкування — Everyday Talk",
      "phrases": [
        { "en": "No worries.", "uk": "Не проблема." },
        { "en": "My bad.", "uk": "Моя вина." },
        { "en": "Hang on.", "uk": "Зачекай." },
        { "en": "Hold on.", "uk": "Секунду." },
        { "en": "Take your time.", "uk": "Не поспішай." },
        { "en": "After you.", "uk": "Після вас." },
        { "en": "Help yourself.", "uk": "Пригощайся." },
        { "en": "I'm starving.", "uk": "Я страшенно голодний." },
        { "en": "I'm beat.", "uk": "Я виснажений." },
        { "en": "Easy does it.", "uk": "Обережніше." },
        { "en": "Here you go.", "uk": "Ось, будь ласка." },
        { "en": "I'm on my way.", "uk": "Я вже в дорозі." },
        { "en": "Give me a second.", "uk": "Дайте мені хвилинку." },
        { "en": "I'll be right back.", "uk": "Я зараз повернуся." },
        { "en": "I'm in a hurry.", "uk": "Я поспішаю." },
        { "en": "How does it work?", "uk": "Як це працює?" },
        { "en": "Can I try it on?", "uk": "Можна це приміряти?" },
        { "en": "Keep the change.", "uk": "Решти не потрібно." },
        { "en": "I'm just looking.", "uk": "Я просто дивлюся." },
        { "en": "I'll keep in touch.", "uk": "Я буду на зв'язку." }
      ]
    },
    "phrase-appraisal": {
      "title": "Оцінка та побажання — Praise and Wishes",
      "phrases": [
        { "en": "Lucky you!", "uk": "Пощастило ж тобі." },
        { "en": "Good for you!", "uk": "Молодець! / Класно!" },
        { "en": "You nailed it.", "uk": "Ти чудово впорався." },
        { "en": "That's the spirit!", "uk": "Оце правильний настрій!" },
        { "en": "Close enough.", "uk": "Майже." },
        { "en": "What a relief!", "uk": "Яке полегшення." },
        { "en": "So far, so good.", "uk": "Поки що все добре." },
        { "en": "No big deal.", "uk": "Дрібниці." },
        { "en": "I'm good.", "uk": "Ні, дякую / У мене все є." },
        { "en": "I'm all set.", "uk": "Усе готово / Мені більше нічого не потрібно." },
        { "en": "It's not a big deal.", "uk": "Нічого страшного." },
        { "en": "I'm used to it.", "uk": "Я до цього звик / звикла." },
        { "en": "I can't wait!", "uk": "Не можу дочекатися!" },
        { "en": "I'm all ears.", "uk": "Я уважно слухаю." },
        { "en": "Take it easy.", "uk": "Не хвилюйтеся. / Розслабтеся." },
        { "en": "Let's call it a day.", "uk": "На сьогодні досить." }
      ]
    },
    "phrase-tenses": {
      "title": "Таблиця часів — Tenses Table",
      "phrases": [
        { "en": "I ate an apple.", "uk": "Я з'їв яблуко." },
        { "en": "I eat an apple.", "uk": "Я їм яблуко (регулярно)." },
        { "en": "I will eat an apple.", "uk": "Я з'їм яблуко." },
        { "en": "I was eating an apple.", "uk": "Я їв яблуко (у той момент)." },
        { "en": "I am eating an apple.", "uk": "Я їм яблуко (зараз)." },
        { "en": "I will be eating an apple.", "uk": "Я їстиму яблуко (у той момент)." },
        { "en": "I had eaten an apple.", "uk": "Я з'їв яблуко (до іншої дії в минулому)." },
        { "en": "I have eaten an apple.", "uk": "Я вже з'їв яблуко." },
        { "en": "I will have eaten an apple.", "uk": "Я вже з'їм яблуко (до моменту в майбутньому)." },
        { "en": "I had been eating an apple.", "uk": "Я їв яблуко певний час (до моменту в минулому)." },
        { "en": "I have been eating an apple.", "uk": "Я їм яблуко вже певний час." },
        { "en": "I will have been eating an apple.", "uk": "Я їстиму яблуко вже певний час." }
      ]
    },
    "phrase-pro": {
      "title": "Кажи як профі — Normal vs Pro",
      "phrases": [
        { "en": "I'm coming.", "uk": "Вже йду." },
        { "en": "I'll try.", "uk": "Спробую." },
        { "en": "I'll make an effort.", "uk": "Докладу зусиль." },
        { "en": "I'm leaving.", "uk": "Я йду." },
        { "en": "I'm heading out.", "uk": "Вирушаю." },
        { "en": "Call me.", "uk": "Подзвони мені." },
        { "en": "Give me a call.", "uk": "Зателефонуй мені." },
        { "en": "Listen to me.", "uk": "Послухай мене." },
        { "en": "Please hear me out.", "uk": "Будь ласка, вислухай мене." },
        { "en": "It's too much.", "uk": "Це занадто." },
        { "en": "It's overwhelming.", "uk": "Це приголомшує." },
        { "en": "I'm scared.", "uk": "Мені страшно." },
        { "en": "I'm anxious.", "uk": "Я тривожуся." },
        { "en": "Come quickly.", "uk": "Іди швидко." },
        { "en": "Please come promptly.", "uk": "Будь ласка, приходь швидко." },
        { "en": "Be careful.", "uk": "Будь обережний." },
        { "en": "Please be cautious.", "uk": "Будь ласка, будьте обачні." },
        { "en": "I forgot.", "uk": "Я забув." },
        { "en": "It slipped my mind.", "uk": "Це вилетіло з голови." },
        { "en": "Not now.", "uk": "Не зараз." },
        { "en": "This isn't the right time.", "uk": "Зараз невдалий момент." },
        { "en": "Stop it.", "uk": "Припини." },
        { "en": "Please discontinue.", "uk": "Будь ласка, припиніть." },
        { "en": "Sit down.", "uk": "Сідай." },
        { "en": "Please take a seat.", "uk": "Будь ласка, сідайте." },
        { "en": "Stand up.", "uk": "Встань." },
        { "en": "Please rise.", "uk": "Будь ласка, встаньте." },
        { "en": "I don't know.", "uk": "Я не знаю." },
        { "en": "Wait a minute.", "uk": "Зачекай хвилинку." },
        { "en": "Please give me a moment.", "uk": "Дайте мені хвилинку, будь ласка." },
        { "en": "Hurry up.", "uk": "Поспішай." },
        { "en": "Please make haste.", "uk": "Будь ласка, покваптеся." },
        { "en": "I'm busy.", "uk": "Я зайнятий." },
        { "en": "I'm occupied.", "uk": "Я маю справи." },
        { "en": "What do you want?", "uk": "Чого ти хочеш?" },
        { "en": "What can I do for you?", "uk": "Чим можу допомогти?" },
        { "en": "It's okay.", "uk": "Все гаразд." },
        { "en": "That's acceptable.", "uk": "Це прийнятно." },
        { "en": "I'm tired.", "uk": "Я втомився." },
        { "en": "I'm exhausted.", "uk": "Я виснажений." },
        { "en": "I'm angry.", "uk": "Я злий." },
        { "en": "I'm upset.", "uk": "Я засмучений." },
        { "en": "I like it.", "uk": "Мені подобається." },
        { "en": "I'm fond of it.", "uk": "Я це дуже люблю." },
        { "en": "I don't like it.", "uk": "Мені не подобається." },
        { "en": "I'm not fond of it.", "uk": "Мені це не до вподоби." },
        { "en": "It's hard.", "uk": "Це важко." },
        { "en": "It's challenging.", "uk": "Це складне завдання." },
        { "en": "It's easy.", "uk": "Це легко." },
        { "en": "It's straightforward.", "uk": "Це просто і зрозуміло." },
        { "en": "Help me.", "uk": "Допоможи мені." },
        { "en": "Could you assist me?", "uk": "Не могли б ви допомогти?" },
        { "en": "Leave me alone.", "uk": "Залиш мене." },
        { "en": "Please give me some space.", "uk": "Дайте мені трохи простору." },
        { "en": "I agree.", "uk": "Я згоден." },
        { "en": "I'm in agreement.", "uk": "Я поділяю цю думку." },
        { "en": "Tell me the truth.", "uk": "Скажи правду." },
        { "en": "Please be honest with me.", "uk": "Будь ласка, будь чесним зі мною." },
        { "en": "That will suffice.", "uk": "Цього буде достатньо." },
        { "en": "I'm confused.", "uk": "Я розгублений." },
        { "en": "I'm perplexed.", "uk": "Я спантеличений." }
      ]
    },
    "phrase-polite": {
      "title": "Ввічливе прохання — Polite Requests",
      "phrases": [
        { "en": "Please have a seat.", "uk": "Будь ласка, сідайте." },
        { "en": "Could you please stand up?", "uk": "Не могли б ви встати?" },
        { "en": "Be quiet.", "uk": "Тихо." },
        { "en": "Could you please be quiet?", "uk": "Не могли б ви говорити тихіше?" },
        { "en": "Could you please listen to me?", "uk": "Не могли б ви мене вислухати?" },
        { "en": "Do it now.", "uk": "Зроби це зараз." },
        { "en": "Could you please do it now?", "uk": "Не могли б ви зробити це зараз?" },
        { "en": "Come here.", "uk": "Іди сюди." },
        { "en": "Could you please come here?", "uk": "Не могли б ви підійти?" },
        { "en": "Go away.", "uk": "Іди геть." },
        { "en": "Would you mind giving me some space, please?", "uk": "Не могли б ви дати мені трохи простору?" },
        { "en": "Give it to me.", "uk": "Дай мені це." },
        { "en": "Could you please give it to me?", "uk": "Не могли б ви передати це мені?" },
        { "en": "Answer me.", "uk": "Відповідай." },
        { "en": "Could you please answer me?", "uk": "Не могли б ви відповісти?" },
        { "en": "Explain this.", "uk": "Поясни це." },
        { "en": "Could you please explain this?", "uk": "Не могли б ви це пояснити?" },
        { "en": "Could you please help me?", "uk": "Не могли б ви допомогти?" },
        { "en": "Fix this.", "uk": "Полагодь це." },
        { "en": "Could you please fix this?", "uk": "Не могли б ви це полагодити?" },
        { "en": "Send it today.", "uk": "Надішли сьогодні." },
        { "en": "Could you please send it today?", "uk": "Не могли б ви надіслати це сьогодні?" },
        { "en": "Finish it.", "uk": "Закінчи це." },
        { "en": "Could you please finish it?", "uk": "Не могли б ви це завершити?" },
        { "en": "Would you mind leaving me alone, please?", "uk": "Не могли б ви залишити мене саму?" },
        { "en": "Wait.", "uk": "Чекай." },
        { "en": "Could you please wait a moment?", "uk": "Не могли б ви зачекати хвилинку?" },
        { "en": "Give me water.", "uk": "Дай води." },
        { "en": "Could I have some water, please?", "uk": "Можна мені води, будь ласка?" },
        { "en": "Don't do that.", "uk": "Не роби цього." },
        { "en": "Please don't do that.", "uk": "Будь ласка, не робіть цього." },
        { "en": "Move.", "uk": "Посунься." },
        { "en": "Excuse me, could you move a little?", "uk": "Перепрошую, не могли б ви посунутися?" },
        { "en": "I want this.", "uk": "Я хочу це." },
        { "en": "I'd like this, please.", "uk": "Я хотів би це, будь ласка." },
        { "en": "Open the door.", "uk": "Відчини двері." },
        { "en": "Would you mind opening the door?", "uk": "Не могли б ви відчинити двері?" },
        { "en": "Close it.", "uk": "Закрий це." },
        { "en": "Could you please close it?", "uk": "Не могли б ви це зачинити?" },
        { "en": "Tell me.", "uk": "Скажи мені." },
        { "en": "Could you tell me, please?", "uk": "Не могли б ви мені сказати?" },
        { "en": "Could you give me a call, please?", "uk": "Не могли б ви мені зателефонувати?" },
        { "en": "I disagree.", "uk": "Я не згоден." },
        { "en": "I'm afraid I don't agree.", "uk": "Боюся, я не погоджуюся." },
        { "en": "You're wrong.", "uk": "Ти помиляєшся." },
        { "en": "I think there might be a mistake.", "uk": "Гадаю, тут може бути помилка." },
        { "en": "Take your time, but please be quick.", "uk": "Не поспішайте, але, будь ласка, швидше." },
        { "en": "Repeat that.", "uk": "Повтори." },
        { "en": "Could you say that again, please?", "uk": "Не могли б ви повторити?" },
        { "en": "Stop talking.", "uk": "Припини говорити." },
        { "en": "Could we keep it down, please?", "uk": "Може, говоритимемо тихіше?" }
      ]
    },
    "phrase-replies": {
      "title": "Короткі відповіді — Short Replies",
      "phrases": [
        { "en": "Nice to meet you.", "uk": "Приємно познайомитися." },
        { "en": "Likewise.", "uk": "Взаємно." },
        { "en": "Welcome!", "uk": "Ласкаво просимо!" },
        { "en": "Glad to have you.", "uk": "Раді вас бачити." },
        { "en": "Excuse me.", "uk": "Перепрошую." },
        { "en": "Pardon me.", "uk": "Вибачте." },
        { "en": "Please.", "uk": "Будь ласка." },
        { "en": "Sure.", "uk": "Звісно." },
        { "en": "Of course.", "uk": "Звичайно." },
        { "en": "Definitely.", "uk": "Безумовно." },
        { "en": "Well done!", "uk": "Молодець!" },
        { "en": "Great job!", "uk": "Чудова робота!" },
        { "en": "I understand.", "uk": "Я розумію." },
        { "en": "Got it.", "uk": "Зрозумів." },
        { "en": "That's okay.", "uk": "Все гаразд." },
        { "en": "It's fine.", "uk": "Нормально." },
        { "en": "No problem.", "uk": "Немає проблем." },
        { "en": "All good.", "uk": "Все добре." },
        { "en": "I miss you.", "uk": "Я сумую за тобою." },
        { "en": "Miss you too.", "uk": "Теж сумую." },
        { "en": "Good night.", "uk": "На добраніч." },
        { "en": "Night.", "uk": "Добраніч." },
        { "en": "See you tomorrow.", "uk": "Побачимось завтра." },
        { "en": "See you then.", "uk": "До зустрічі." },
        { "en": "Perfect!", "uk": "Чудово!" },
        { "en": "Tied up.", "uk": "Зайнятий по вуха." },
        { "en": "Let me know.", "uk": "Дай знати." },
        { "en": "Keep me posted.", "uk": "Тримай мене в курсі." },
        { "en": "Thank you.", "uk": "Дякую." },
        { "en": "Anytime.", "uk": "Завжди будь ласка." },
        { "en": "I'm sorry.", "uk": "Пробач." },
        { "en": "Good morning.", "uk": "Доброго ранку." },
        { "en": "Morning.", "uk": "Ранку." },
        { "en": "Thank you so much.", "uk": "Дуже дякую." },
        { "en": "My pleasure.", "uk": "Мені приємно." },
        { "en": "Sorry for the delay.", "uk": "Вибач за затримку." },
        { "en": "Talk to you later.", "uk": "Поговоримо пізніше." },
        { "en": "Catch you later.", "uk": "До зв'язку." },
        { "en": "That's funny.", "uk": "Це смішно." },
        { "en": "So true.", "uk": "Так і є." },
        { "en": "See you later.", "uk": "До зустрічі." },
        { "en": "Catch you soon.", "uk": "Скоро побачимось." },
        { "en": "Good luck!", "uk": "Щасти!" },
        { "en": "Same here.", "uk": "Я теж." },
        { "en": "How are you?", "uk": "Як справи?" },
        { "en": "What's up?", "uk": "Що нового?" },
        { "en": "Not much.", "uk": "Та нічого." },
        { "en": "Can you help me?", "uk": "Можеш допомогти?" },
        { "en": "Sure thing.", "uk": "Звісно." },
        { "en": "That's amazing.", "uk": "Це чудово." },
        { "en": "Totally.", "uk": "Абсолютно." },
        { "en": "Take care.", "uk": "Бережи себе." },
        { "en": "You too.", "uk": "Ти теж." },
        { "en": "Let's go.", "uk": "Ходімо." },
        { "en": "Are you ready?", "uk": "Ти готовий?" },
        { "en": "All set.", "uk": "Готовий." },
        { "en": "Where are you?", "uk": "Ти де?" },
        { "en": "On the way.", "uk": "В дорозі." }
      ]
    },
    "phrase-advanced": {
      "title": "Просунуті фрази — Advanced Phrases",
      "phrases": [
        { "en": "Bye.", "uk": "Бувай." },
        { "en": "I'm terrified.", "uk": "Я в жаху." },
        { "en": "I'm very happy.", "uk": "Я дуже щасливий." },
        { "en": "I'm delighted.", "uk": "Я в захваті." },
        { "en": "It's your choice.", "uk": "Твій вибір." },
        { "en": "It's very easy.", "uk": "Це дуже легко." },
        { "en": "It's a piece of cake.", "uk": "Це простіше простого." },
        { "en": "I'm tied up.", "uk": "Я зайнятий по вуха." },
        { "en": "I'm very hungry.", "uk": "Я дуже голодний." },
        { "en": "Hold on a second.", "uk": "Секундочку." },
        { "en": "How have you been?", "uk": "Як ти жив увесь цей час?" },
        { "en": "I really appreciate it.", "uk": "Я дуже це ціную." },
        { "en": "I sincerely apologize.", "uk": "Я щиро перепрошую." },
        { "en": "I'm happy.", "uk": "Я щасливий." },
        { "en": "I'm over the moon.", "uk": "Я на сьомому небі." },
        { "en": "Shake a leg!", "uk": "Ворушися!" },
        { "en": "I get the idea.", "uk": "Я вловив суть." },
        { "en": "I don't understand.", "uk": "Я не розумію." },
        { "en": "I'm a bit lost.", "uk": "Я трохи заплутався." },
        { "en": "I'm furious.", "uk": "Я розлючений." },
        { "en": "I'm puzzled.", "uk": "Я спантеличений." },
        { "en": "I'm worried.", "uk": "Я хвилююся." },
        { "en": "I'm concerned.", "uk": "Мене це непокоїть." },
        { "en": "I'm disappointed.", "uk": "Я розчарований." },
        { "en": "I'm let down.", "uk": "Мене підвели." },
        { "en": "I'm bored.", "uk": "Мені нудно." },
        { "en": "I'm feeling uninterested.", "uk": "Мені геть нецікаво." },
        { "en": "I'm ready.", "uk": "Я готовий." },
        { "en": "I'm not ready.", "uk": "Я не готовий." },
        { "en": "I need more time.", "uk": "Мені потрібно більше часу." },
        { "en": "I'm interested.", "uk": "Мені цікаво." },
        { "en": "It fascinates me.", "uk": "Це мене захоплює." },
        { "en": "I'm not interested.", "uk": "Мені нецікаво." },
        { "en": "It doesn't appeal to me.", "uk": "Це мене не приваблює." },
        { "en": "I'll give it some thought.", "uk": "Я це обміркую." },
        { "en": "Calm down.", "uk": "Заспокойся." },
        { "en": "Take a deep breath.", "uk": "Зроби глибокий вдих." },
        { "en": "I'm on the same page.", "uk": "Ми думаємо однаково." },
        { "en": "I beg to differ.", "uk": "Дозволю собі не погодитись." },
        { "en": "Come over here.", "uk": "Підійди сюди." },
        { "en": "I'm unsure.", "uk": "Я не впевнений." },
        { "en": "I'm doubtful.", "uk": "У мене є сумніви." },
        { "en": "Stay alert.", "uk": "Будь пильним." }
      ]
    },
    "phrase-units": {
      "title": "Одиниці часу — Units of Time",
      "phrases": [
        { "en": "1 minute = 60 seconds", "uk": "хвилина — 60 секунд" },
        { "en": "1 hour = 60 minutes", "uk": "година — 60 хвилин" },
        { "en": "1 day = 24 hours", "uk": "доба — 24 години" },
        { "en": "1 week = 7 days", "uk": "тиждень — 7 днів" },
        { "en": "1 fortnight = 14 days", "uk": "два тижні — 14 днів" },
        { "en": "1 month = 30 days", "uk": "місяць — 30 днів" },
        { "en": "1 bimester = 2 months", "uk": "два місяці" },
        { "en": "1 trimester = 3 months", "uk": "тримест — 3 місяці" },
        { "en": "1 semester = 6 months", "uk": "семестр — 6 місяців" },
        { "en": "1 year = 12 months", "uk": "рік — 12 місяців" },
        { "en": "1 decade = 10 years", "uk": "десятиліття — 10 років" },
        { "en": "1 century = 100 years", "uk": "століття — 100 років" },
        { "en": "1 millennium = 1000 years", "uk": "тисячоліття — 1000 років" },
        { "en": "1 score = 20 years", "uk": "двадцятиліття — 20 років" },
        { "en": "1 olympiad = 4 years", "uk": "олімпіада — 4 роки" },
        { "en": "1 biennium = 2 years", "uk": "дворіччя — 2 роки" },
        { "en": "1 lustrum = 5 years", "uk": "п'ятиріччя — 5 років" },
        { "en": "1 microsecond = 0.000001 second", "uk": "мікросекунда" },
        { "en": "1 millisecond = 0.001 second", "uk": "мілісекунда" },
        { "en": "1 nanosecond = 0.000000001 second", "uk": "наносекунда" },
        { "en": "1 leap year = 366 days", "uk": "високосний рік — 366 днів" },
        { "en": "1 quarter = 3 months", "uk": "квартал — 3 місяці" },
        { "en": "1 quinquennium = 5 years", "uk": "п'ятиріччя — 5 років" },
        { "en": "1 jubilation period = 50 years", "uk": "ювілейний період — 50 років" },
        { "en": "1 eon = very long time", "uk": "еон — дуже довгий час" },
        { "en": "1 morning = before noon", "uk": "ранок — до полудня" },
        { "en": "1 evening = after noon", "uk": "вечір — після полудня" },
        { "en": "1 noon = 12:00 PM", "uk": "полудень" },
        { "en": "1 midnight = 12:00 AM", "uk": "північ" },
        { "en": "1 fiscal year = 12 months", "uk": "фінансовий рік — 12 місяців" }
      ]
    },
    "phrase-degree": {
      "title": "Ступені порівняння — Degrees of Comparison",
      "phrases": [
        { "en": "good — better — best", "uk": "хороший — кращий — найкращий" },
        { "en": "bad — worse — worst", "uk": "поганий — гірший — найгірший" },
        { "en": "beautiful — more beautiful — most beautiful", "uk": "гарний — гарніший — найгарніший" },
        { "en": "important — more important — most important", "uk": "важливий — важливіший — найважливіший" },
        { "en": "high — higher — highest", "uk": "високий — вищий — найвищий" },
        { "en": "long — longer — longest", "uk": "довгий — довший — найдовший" },
        { "en": "tall — taller — tallest", "uk": "високий (на зріст) — вищий — найвищий" },
        { "en": "short — shorter — shortest", "uk": "короткий — коротший — найкоротший" },
        { "en": "soft — softer — softest", "uk": "м'який — м'якший — найм'якший" },
        { "en": "deep — deeper — deepest", "uk": "глибокий — глибший — найглибший" },
        { "en": "happy — happier — happiest", "uk": "щасливий — щасливіший — найщасливіший" },
        { "en": "clever — cleverer — cleverest", "uk": "розумний — розумніший — найрозумніший" },
        { "en": "hot — hotter — hottest", "uk": "гарячий — гарячіший — найгарячіший" },
        { "en": "cold — colder — coldest", "uk": "холодний — холодніший — найхолодніший" },
        { "en": "rich — richer — richest", "uk": "багатий — багатший — найбагатший" },
        { "en": "poor — poorer — poorest", "uk": "бідний — бідніший — найбідніший" },
        { "en": "heavy — heavier — heaviest", "uk": "важкий — важчий — найважчий" },
        { "en": "light — lighter — lightest", "uk": "легкий — легший — найлегший" },
        { "en": "brave — braver — bravest", "uk": "сміливий — сміливіший — найсміливіший" },
        { "en": "sweet — sweeter — sweetest", "uk": "солодкий — солодший — найсолодший" },
        { "en": "little — less — least", "uk": "малий — менший — найменший" },
        { "en": "many / much — more — most", "uk": "багато — більше — найбільше" },
        { "en": "far — farther — farthest", "uk": "далекий — дальший — найдальший" },
        { "en": "late — later — latest", "uk": "пізній — пізніший — найпізніший" }
      ]
    }
  }
};
