const WORD_DATA = {
  "order": {
    "0": "bathroom",
    "1": "actions",
    "2": "verbs-b1",
    "3": "home",
    "4": "days",
    "5": "helping-verbs",
    "6": "friends",
    "7": "emotions",
    "8": "pronouns",
    "9": "health",
    "10": "toys",
    "11": "tools",
    "12": "food",
    "13": "coffee",
    "14": "fairy-tales",
    "15": "collocations-make-do",
    "16": "collocations-take-get",
    "17": "collocations-say-tell",
    "18": "collocations-hear-listen",
    "19": "colors",
    "20": "insects",
    "21": "space",
    "22": "kitchenware",
    "23": "summer",
    "24": "people",
    "25": "materials",
    "26": "furniture",
    "27": "city",
    "28": "months",
    "29": "sea-animals",
    "30": "music",
    "31": "drinks",
    "32": "face",
    "33": "vegetables",
    "34": "clothes",
    "35": "description",
    "36": "questions",
    "37": "travel",
    "38": "weather",
    "39": "position",
    "40": "seasons",
    "41": "everyday-objects",
    "42": "greetings",
    "43": "prepositions",
    "44": "nature",
    "45": "adverbs",
    "46": "frequency-adverbs",
    "47": "professions",
    "48": "birds",
    "49": "plants",
    "50": "flowers",
    "51": "world",
    "52": "holidays",
    "53": "family",
    "54": "function-words",
    "55": "sweets",
    "56": "conjunctions",
    "57": "sports",
    "58": "idioms",
    "59": "state",
    "60": "pets",
    "61": "wild-animals",
    "62": "body",
    "63": "transport",
    "64": "farm-animals",
    "65": "shapes",
    "66": "phrasal-verbs",
    "67": "fruits",
    "68": "time",
    "69": "time-of-day",
    "70": "time-adverbs",
    "71": "numbers",
    "72": "school"
  },
  "categories": {
    "bathroom": {
      "title": "Ванна кімната — Bathroom",
      "words": [
        { "uk": "мило", "en": "soap" },
        { "uk": "рушник", "en": "towel" },
        { "uk": "зубна щітка", "en": "toothbrush" },
        { "uk": "зубна паста", "en": "toothpaste" },
        { "uk": "шампунь", "en": "shampoo" },
        { "uk": "гребінець", "en": "hairbrush" },
        { "uk": "душ", "en": "shower" },
        { "uk": "кран", "en": "valve" }
      ]
    },
    "actions": {
      "title": "Дії — Actions",
      "words": [
        { "uk": "йти", "en": "go" },
        { "uk": "бігти", "en": "run" },
        { "uk": "стрибати", "en": "jump" },
        { "uk": "плавати", "en": "swim" },
        { "uk": "літати", "en": "fly" },
        { "uk": "їсти", "en": "eat" },
        { "uk": "пити; напій", "en": "drink" },
        { "uk": "спати", "en": "sleep" },
        { "uk": "читати", "en": "read" },
        { "uk": "писати", "en": "write" },
        { "uk": "малювати", "en": "draw" },
        { "uk": "співати", "en": "sing" },
        { "uk": "танцювати", "en": "dance" },
        { "uk": "грати", "en": "play" },
        { "uk": "дивитися", "en": "look" },
        { "uk": "слухати", "en": "listen" },
        { "uk": "говорити", "en": "talk" },
        { "uk": "думати", "en": "think" },
        { "uk": "знати", "en": "know" },
        { "uk": "хотіти", "en": "want" },
        { "uk": "любити", "en": "love" },
        { "uk": "дати", "en": "give" },
        { "uk": "брати", "en": "take" },
        { "uk": "відкривати", "en": "open" },
        { "uk": "закривати", "en": "close" },
        { "uk": "сидіти", "en": "sit" },
        { "uk": "стояти", "en": "stand" },
        { "uk": "лежати", "en": "lie down" },
        { "uk": "чекати", "en": "wait" },
        { "uk": "шукати", "en": "search" },
        { "uk": "знаходити", "en": "find" },
        { "uk": "носити", "en": "carry" },
        { "uk": "будувати", "en": "build" },
        { "uk": "мити", "en": "wash" },
        { "uk": "готувати", "en": "cook" },
        { "uk": "різати", "en": "cut" },
        { "uk": "кидати", "en": "throw" },
        { "uk": "ловити", "en": "catch" },
        { "uk": "ховати", "en": "hide" },
        { "uk": "допомагати", "en": "help" },
        { "uk": "вчити", "en": "learn" },
        { "uk": "пам'ятати", "en": "remember" },
        { "uk": "забувати", "en": "forget" },
        { "uk": "починати", "en": "start" },
        { "uk": "закінчувати", "en": "finish" },
        { "uk": "робити", "en": "do" },
        { "uk": "бачити", "en": "see" },
        { "uk": "чути", "en": "hear" },
        { "uk": "відповідати", "en": "answer" },
        { "uk": "питати", "en": "ask" },
        { "uk": "сміятися", "en": "laugh" },
        { "uk": "плакати", "en": "cry" },
        { "uk": "посміхатися", "en": "smile" },
        { "uk": "обіймати", "en": "hug" },
        { "uk": "цілувати", "en": "kiss" },
        { "uk": "мріяти", "en": "dream" },
        { "uk": "діяти; розігрувати", "en": "act" },
        { "uk": "перевіряти", "en": "check" },
        { "uk": "жити", "en": "live" },
        { "uk": "потребувати", "en": "need" },
        { "uk": "покласти", "en": "put" },
        { "uk": "повторювати", "en": "repeat" },
        { "uk": "казати", "en": "say" },
        { "uk": "показати", "en": "show" },
        { "uk": "торкатися", "en": "touch" },
        { "uk": "обводити", "en": "trace" },
        { "uk": "позначити галочкою", "en": "tick" },
        { "uk": "дивитися", "en": "watch" }
      ]
    },
    "verbs-b1": {
      "title": "Дієслова — Verbs (B1)",
      "words": [
        { "uk": "досягати", "en": "achieve" },
        { "uk": "уникати", "en": "avoid" },
        { "uk": "покращувати", "en": "improve" },
        { "uk": "справлятися", "en": "manage" },
        { "uk": "заохочувати", "en": "encourage" },
        { "uk": "зменшувати", "en": "reduce" },
        { "uk": "збільшувати", "en": "increase" },
        { "uk": "забезпечувати", "en": "provide" },
        { "uk": "залежати", "en": "depend" },
        { "uk": "пропонувати", "en": "suggest" },
        { "uk": "скаржитися", "en": "complain" },
        { "uk": "відмовлятися", "en": "refuse" },
        { "uk": "готуватися", "en": "prepare" },
        { "uk": "усвідомлювати", "en": "realize" },
        { "uk": "рекомендувати", "en": "recommend" },
        { "uk": "впізнавати", "en": "recognize" },
        { "uk": "відповідати", "en": "respond" },
        { "uk": "виживати", "en": "survive" },
        { "uk": "підтримувати", "en": "support" },
        { "uk": "попереджати", "en": "warn" }
      ]
    },
    "home": {
      "title": "Дім та кімнати — Home & Rooms",
      "words": [
        { "uk": "дім", "en": "house" },
        { "uk": "кімната", "en": "room" },
        { "uk": "кухня", "en": "kitchen" },
        { "uk": "спальня", "en": "bedroom" },
        { "uk": "ванна", "en": "bathroom" },
        { "uk": "вітальня", "en": "living room" },
        { "uk": "коридор", "en": "hallway" },
        { "uk": "балкон", "en": "balcony" },
        { "uk": "дах", "en": "roof" },
        { "uk": "підлога", "en": "floor" },
        { "uk": "стіна", "en": "wall" },
        { "uk": "стеля", "en": "ceiling" },
        { "uk": "сходи", "en": "stairs" },
        { "uk": "гараж", "en": "garage" }
      ]
    },
    "days": {
      "title": "Дні тижня — Days of Week",
      "words": [
        { "uk": "понеділок", "en": "Monday" },
        { "uk": "вівторок", "en": "Tuesday" },
        { "uk": "середа", "en": "Wednesday" },
        { "uk": "четвер", "en": "Thursday" },
        { "uk": "п'ятниця", "en": "Friday" },
        { "uk": "субота", "en": "Saturday" },
        { "uk": "неділя", "en": "Sunday" }
      ]
    },
    "helping-verbs": {
      "title": "Допоміжні дієслова — Helping Verbs",
      "words": [
        { "uk": "можу", "en": "can" },
        { "uk": "має", "en": "has" },
        { "uk": "мати", "en": "have" },
        { "uk": "не є", "en": "isn't" },
        { "uk": "це є", "en": "it's" },
        { "uk": "давай/давайте", "en": "let's" }
      ]
    },
    "friends": {
      "title": "Друзі — Friends",
      "words": [
        { "uk": "знайомий", "en": "acquaintance" },
        { "uk": "однодумці", "en": "like-minded people" },
        { "uk": "надійний", "en": "reliable" },
        { "uk": "сперечатися", "en": "argue" },
        { "uk": "проводити час разом", "en": "hang out" },
        { "uk": "підтримувати зв'язок", "en": "keep in touch" },
        { "uk": "віддалятися", "en": "drift apart" },
        { "uk": "бути поруч, підтримувати", "en": "be there for" },
        { "uk": "обмінятися новинами", "en": "catch up" }
      ]
    },
    "emotions": {
      "title": "Емоції — Emotions",
      "words": [
        { "uk": "радість", "en": "joy" },
        { "uk": "сум", "en": "sadness" },
        { "uk": "страх", "en": "fear" },
        { "uk": "злість", "en": "anger" },
        { "uk": "любов", "en": "love" },
        { "uk": "сміх", "en": "laughter" },
        { "uk": "плач", "en": "crying" },
        { "uk": "здивування", "en": "surprise" },
        { "uk": "гордість", "en": "pride" },
        { "uk": "спокій", "en": "calm" },
        { "uk": "надія", "en": "hope" },
        { "uk": "щастя", "en": "happiness" },
        { "uk": "сором", "en": "shame" },
        { "uk": "ніжність", "en": "tenderness" },
        { "uk": "приголомшений", "en": "overwhelmed" },
        { "uk": "розчарований, засмучений", "en": "frustrated" },
        { "uk": "полегшений", "en": "relieved" },
        { "uk": "тривожний", "en": "anxious" },
        { "uk": "винний", "en": "guilty" },
        { "uk": "присоромлений", "en": "ashamed" },
        { "uk": "вдячний", "en": "grateful" },
        { "uk": "розчарований", "en": "disappointed" },
        { "uk": "збентежений", "en": "embarrassed" },
        { "uk": "ревнивий", "en": "jealous" },
        { "uk": "заздрісний", "en": "envious" },
        { "uk": "роздратований", "en": "irritated" },
        { "uk": "впевнений у собі", "en": "confident" },
        { "uk": "сповнений ентузіазму", "en": "enthusiastic" },
        { "uk": "стурбований", "en": "concerned" },
        { "uk": "шокований", "en": "shocked" },
        { "uk": "дуже задоволений", "en": "delighted" },
        { "uk": "наляканий до жаху", "en": "terrified" },
        { "uk": "задоволений, умиротворений", "en": "content" },
        { "uk": "ображений", "en": "resentful" }
      ]
    },
    "pronouns": {
      "title": "Займенники — Pronouns",
      "words": [
        { "uk": "він", "en": "he" },
        { "uk": "вона", "en": "she" },
        { "uk": "воно", "en": "it" },
        { "uk": "вони", "en": "they" },
        { "uk": "ти/ви", "en": "you" },
        { "uk": "мені/мене", "en": "me" },
        { "uk": "мій/моя/моє", "en": "my" },
        { "uk": "його", "en": "his" },
        { "uk": "це/цей", "en": "this" }
      ]
    },
    "health": {
      "title": "Здоров'я — Health",
      "words": [
        { "uk": "здоров'я", "en": "health" },
        { "uk": "ліки", "en": "medicine" },
        { "uk": "температура", "en": "temperature" },
        { "uk": "кашель", "en": "cough" },
        { "uk": "нежить", "en": "runny nose" },
        { "uk": "біль", "en": "pain" },
        { "uk": "пластир", "en": "Band-Aid" },
        { "uk": "вітамін", "en": "vitamin" },
        { "uk": "болить", "en": "hurts" },
        { "uk": "боліти", "en": "hurt" },
        { "uk": "вправа", "en": "exercise" }
      ]
    },
    "toys": {
      "title": "Іграшки та ігри — Toys & Games",
      "words": [
        { "uk": "м'яч", "en": "ball" },
        { "uk": "лялька", "en": "doll" },
        { "uk": "ведмедик", "en": "teddy bear" },
        { "uk": "кубики", "en": "blocks" },
        { "uk": "пазл", "en": "puzzle" },
        { "uk": "робот", "en": "robot" },
        { "uk": "гра", "en": "game" },
        { "uk": "повітряна куля", "en": "balloon" },
        { "uk": "скакалка", "en": "jump rope" },
        { "uk": "настільна гра", "en": "board game" },
        { "uk": "конструктор", "en": "constructor" },
        { "uk": "іграшка", "en": "toy" },
        { "uk": "повітряний змій", "en": "kite" }
      ]
    },
    "tools": {
      "title": "Інструменти — Tools",
      "words": [
        { "uk": "молоток", "en": "hammer" },
        { "uk": "ножиці", "en": "scissors" },
        { "uk": "клей", "en": "glue" },
        { "uk": "голка", "en": "needle" },
        { "uk": "нитка", "en": "thread" },
        { "uk": "пензлик", "en": "brush" },
        { "uk": "лопата", "en": "shovel" },
        { "uk": "відро", "en": "bucket" },
        { "uk": "фарба", "en": "paint" },
        { "uk": "цвях", "en": "nail" }
      ]
    },
    "food": {
      "title": "Їжа та страви — Food & Meals",
      "words": [
        { "uk": "хліб", "en": "bread" },
        { "uk": "каша", "en": "porridge" },
        { "uk": "суп", "en": "soup" },
        { "uk": "їжа", "en": "food" },
        { "uk": "сніданок", "en": "breakfast" },
        { "uk": "обід", "en": "lunch" },
        { "uk": "вечеря", "en": "dinner" },
        { "uk": "рис", "en": "rice" },
        { "uk": "макарони", "en": "pasta" },
        { "uk": "м'ясо", "en": "meat" },
        { "uk": "сир", "en": "cheese" },
        { "uk": "масло", "en": "butter" },
        { "uk": "яйце", "en": "egg" },
        { "uk": "борщ", "en": "borscht" },
        { "uk": "вареник", "en": "dumpling" },
        { "uk": "сіль", "en": "salt" },
        { "uk": "піца", "en": "pizza" },
        { "uk": "бутерброд", "en": "sandwich" },
        { "uk": "млинець", "en": "pancake" },
        { "uk": "сметана", "en": "sour cream" },
        { "uk": "желе", "en": "jelly" },
        { "uk": "горіхи", "en": "nuts" },
        { "uk": "ковбаса", "en": "sausage" }
      ]
    },
    "coffee": {
      "title": "Кава — Coffee",
      "words": [
        { "uk": "кава", "en": "coffee" },
        { "uk": "кав'ярня", "en": "coffee shop" },
        { "uk": "бариста", "en": "barista" },
        { "uk": "чашка", "en": "cup" },
        { "uk": "горнятко", "en": "mug" },
        { "uk": "обсмажування", "en": "roast" },
        { "uk": "заварювати", "en": "brew" },
        { "uk": "кофеїн", "en": "caffeine" },
        { "uk": "із собою", "en": "takeaway" },
        { "uk": "молоко", "en": "milk" },
        { "uk": "цукор", "en": "sugar" },
        { "uk": "пінка", "en": "foam" },
        { "uk": "міцний", "en": "strong" },
        { "uk": "замовляти", "en": "order" },
        { "uk": "помішувати", "en": "stir" },
        { "uk": "смак, аромат", "en": "flavor" },
        { "uk": "гіркий", "en": "bitter" },
        { "uk": "солодкий", "en": "sweet" },
        { "uk": "щойно заварений", "en": "freshly brewed" },
        { "uk": "перерва на каву", "en": "coffee break" }
      ]
    },
    "fairy-tales": {
      "title": "Казки — Fairy Tales",
      "words": [
        { "uk": "принцеса", "en": "princess" },
        { "uk": "принц", "en": "prince" },
        { "uk": "король", "en": "king" },
        { "uk": "королева", "en": "queen" },
        { "uk": "дракон", "en": "dragon" },
        { "uk": "лицар", "en": "knight" },
        { "uk": "чарівник", "en": "wizard" },
        { "uk": "замок", "en": "castle" },
        { "uk": "фея", "en": "fairy" },
        { "uk": "казка", "en": "fairy tale" },
        { "uk": "скарб", "en": "treasure" },
        { "uk": "меч", "en": "sword" },
        { "uk": "монстр", "en": "monster" },
        { "uk": "історія", "en": "story" }
      ]
    },
    "collocations-make-do": {
      "title": "Make/Do — Make &amp; Do",
      "words": [
        { "uk": "заробляти гроші", "en": "make money" },
        { "uk": "застеляти ліжко", "en": "make the bed" },
        { "uk": "телефонувати", "en": "make a phone call" },
        { "uk": "складати план", "en": "make a plan" },
        { "uk": "робити помилку", "en": "make a mistake" },
        { "uk": "робити домашнє завдання", "en": "do homework" },
        { "uk": "проводити дослідження", "en": "do research" },
        { "uk": "мити посуд", "en": "do the dishes" },
        { "uk": "вести бізнес", "en": "do business" },
        { "uk": "прати білизну", "en": "do the laundry" }
      ]
    },
    "collocations-take-get": {
      "title": "Take/Get — Take &amp; Get",
      "words": [
        { "uk": "фотографувати", "en": "take a picture" },
        { "uk": "робити перерву", "en": "take a break" },
        { "uk": "робити нотатки", "en": "take notes" },
        { "uk": "приймати душ", "en": "take a shower" },
        { "uk": "дрімати", "en": "take a nap" },
        { "uk": "отримати роботу", "en": "get a job" },
        { "uk": "одружитися", "en": "get married" },
        { "uk": "завагітніти", "en": "get pregnant" },
        { "uk": "загубитися", "en": "get lost" },
        { "uk": "напитися", "en": "get drunk" }
      ]
    },
    "collocations-say-tell": {
      "title": "Say/Tell — Say &amp; Tell",
      "words": [
        { "uk": "сказати ні", "en": "say no" },
        { "uk": "сказати так", "en": "say yes" },
        { "uk": "привітатися", "en": "say hello" },
        { "uk": "казати \"будь ласка\"", "en": "say please" },
        { "uk": "щось сказати", "en": "say something" },
        { "uk": "збрехати", "en": "tell a lie" },
        { "uk": "розповісти жарт", "en": "tell a joke" },
        { "uk": "розповісти історію", "en": "tell a story" },
        { "uk": "розповісти секрет", "en": "tell a secret" },
        { "uk": "сказати правду", "en": "tell the truth" }
      ]
    },
    "collocations-hear-listen": {
      "title": "Hear/Listen — Hear &amp; Listen",
      "words": [
        { "uk": "почути сміх", "en": "hear a laugh" },
        { "uk": "почути дощ", "en": "hear the rain" },
        { "uk": "почути шепіт", "en": "hear a whisper" },
        { "uk": "почути дзвіночок", "en": "hear a bell" },
        { "uk": "почути спів птахів", "en": "hear birds singing" },
        { "uk": "слухати музику", "en": "listen to music" },
        { "uk": "слухати подкаст", "en": "listen to a podcast" },
        { "uk": "слухати новини", "en": "listen to the news" },
        { "uk": "слухати промову", "en": "listen to a speech" },
        { "uk": "слухати радіо", "en": "listen to the radio" }
      ]
    },
    "colors": {
      "title": "Кольори — Colors",
      "words": [
        { "uk": "червоний", "en": "red" },
        { "uk": "синій", "en": "blue" },
        { "uk": "зелений", "en": "green" },
        { "uk": "жовтий", "en": "yellow" },
        { "uk": "білий", "en": "white" },
        { "uk": "чорний", "en": "black" },
        { "uk": "рожевий", "en": "pink" },
        { "uk": "помаранчевий", "en": "orange" },
        { "uk": "фіолетовий", "en": "purple" },
        { "uk": "сірий", "en": "gray" },
        { "uk": "коричневий", "en": "brown" },
        { "uk": "золотий", "en": "gold" },
        { "uk": "срібний", "en": "silver" },
        { "uk": "блакитний", "en": "light blue" },
        { "uk": "колір", "en": "color" }
      ]
    },
    "insects": {
      "title": "Комахи — Insects",
      "words": [
        { "uk": "метелик", "en": "butterfly" },
        { "uk": "бджола", "en": "bee" },
        { "uk": "мураха", "en": "ant" },
        { "uk": "жук", "en": "beetle" },
        { "uk": "комар", "en": "mosquito" },
        { "uk": "павук", "en": "spider" },
        { "uk": "муха", "en": "fly" },
        { "uk": "сонечко", "en": "ladybug" },
        { "uk": "коник", "en": "grasshopper" },
        { "uk": "равлик", "en": "snail" }
      ]
    },
    "space": {
      "title": "Космос — Space",
      "words": [
        { "uk": "космос", "en": "space" },
        { "uk": "планета", "en": "planet" },
        { "uk": "комета", "en": "comet" },
        { "uk": "галактика", "en": "galaxy" },
        { "uk": "телескоп", "en": "telescope" },
        { "uk": "супутник", "en": "satellite" },
        { "uk": "орбіта", "en": "orbit" },
        { "uk": "астероїд", "en": "asteroid" }
      ]
    },
    "kitchenware": {
      "title": "Кухонне приладдя — Kitchenware",
      "words": [
        { "uk": "тарілка", "en": "plate" },
        { "uk": "чашка", "en": "cup" },
        { "uk": "ложка", "en": "spoon" },
        { "uk": "виделка", "en": "fork" },
        { "uk": "ніж", "en": "knife" },
        { "uk": "каструля", "en": "pot" },
        { "uk": "сковорода", "en": "pan" },
        { "uk": "склянка", "en": "glass" },
        { "uk": "чайник", "en": "kettle" },
        { "uk": "миска", "en": "bowl" }
      ]
    },
    "summer": {
      "title": "Літо — Summer",
      "words": [
        { "uk": "відпустка, канікули", "en": "vacation" },
        { "uk": "фестиваль", "en": "festival" },
        { "uk": "на відкритому повітрі", "en": "outdoors" },
        { "uk": "хвиля спеки", "en": "heatwave" },
        { "uk": "вологість", "en": "humidity" },
        { "uk": "легкий вітерець", "en": "breeze" },
        { "uk": "сонячний опік", "en": "sunburn" },
        { "uk": "сонцезахисний крем", "en": "sunscreen" },
        { "uk": "кемпінг", "en": "camping" },
        { "uk": "піший похід", "en": "hiking" },
        { "uk": "морське узбережжя", "en": "seaside" },
        { "uk": "розслаблюючий", "en": "relaxing" },
        { "uk": "освіжаючий", "en": "refreshing" },
        { "uk": "переповнений людьми", "en": "crowded" },
        { "uk": "незабутній", "en": "memorable" },
        { "uk": "досліджувати", "en": "explore" }
      ]
    },
    "people": {
      "title": "Люди — People",
      "words": [
        { "uk": "друг", "en": "friend" },
        { "uk": "дівчинка", "en": "girl" },
        { "uk": "хлопчик", "en": "boy" },
        { "uk": "жінка", "en": "woman" },
        { "uk": "чоловік", "en": "man" },
        { "uk": "людина", "en": "person" },
        { "uk": "сусід", "en": "neighbor" },
        { "uk": "подруга", "en": "girlfriend" },
        { "uk": "немовля", "en": "infant" },
        { "uk": "хлопець", "en": "guy" },
        { "uk": "діти", "en": "children" },
        { "uk": "партнер", "en": "partner" },
        { "uk": "ім'я", "en": "name" }
      ]
    },
    "materials": {
      "title": "Матеріали — Materials",
      "words": [
        { "uk": "дерево", "en": "wood" },
        { "uk": "метал", "en": "metal" },
        { "uk": "скло", "en": "glass" },
        { "uk": "папір", "en": "paper" },
        { "uk": "тканина", "en": "fabric" },
        { "uk": "пластик", "en": "plastic" },
        { "uk": "гума", "en": "rubber" },
        { "uk": "глина", "en": "clay" },
        { "uk": "вовна", "en": "wool" },
        { "uk": "бавовна", "en": "cotton" }
      ]
    },
    "furniture": {
      "title": "Меблі — Furniture",
      "words": [
        { "uk": "стіл", "en": "table" },
        { "uk": "стілець", "en": "chair" },
        { "uk": "ліжко", "en": "bed" },
        { "uk": "шафа", "en": "wardrobe" },
        { "uk": "диван", "en": "sofa" },
        { "uk": "полиця", "en": "shelf" },
        { "uk": "дзеркало", "en": "mirror" },
        { "uk": "лампа", "en": "lamp" },
        { "uk": "килим", "en": "carpet" },
        { "uk": "годинник", "en": "clock" },
        { "uk": "телевізор", "en": "TV" },
        { "uk": "холодильник", "en": "fridge" },
        { "uk": "подушка", "en": "pillow" },
        { "uk": "ковдра", "en": "blanket" }
      ]
    },
    "city": {
      "title": "Місто — City",
      "words": [
        { "uk": "місто", "en": "city" },
        { "uk": "вулиця", "en": "street" },
        { "uk": "парк", "en": "park" },
        { "uk": "магазин", "en": "shop" },
        { "uk": "лікарня", "en": "hospital" },
        { "uk": "бібліотека", "en": "library" },
        { "uk": "музей", "en": "museum" },
        { "uk": "театр", "en": "theater" },
        { "uk": "зоопарк", "en": "zoo" },
        { "uk": "аптека", "en": "pharmacy" },
        { "uk": "пошта", "en": "post office" },
        { "uk": "банк", "en": "bank" },
        { "uk": "церква", "en": "church" },
        { "uk": "міст", "en": "bridge" },
        { "uk": "фонтан", "en": "fountain" },
        { "uk": "площа", "en": "square" },
        { "uk": "дитячий майданчик", "en": "playground" },
        { "uk": "ресторан", "en": "restaurant" },
        { "uk": "кінотеатр", "en": "cinema" },
        { "uk": "стадіон", "en": "stadium" },
        { "uk": "канал", "en": "channel" }
      ]
    },
    "months": {
      "title": "Місяці — Months",
      "words": [
        { "uk": "січень", "en": "January" },
        { "uk": "лютий", "en": "February" },
        { "uk": "березень", "en": "March" },
        { "uk": "квітень", "en": "April" },
        { "uk": "травень", "en": "May" },
        { "uk": "червень", "en": "June" },
        { "uk": "липень", "en": "July" },
        { "uk": "серпень", "en": "August" },
        { "uk": "вересень", "en": "September" },
        { "uk": "жовтень", "en": "October" },
        { "uk": "листопад", "en": "November" },
        { "uk": "грудень", "en": "December" }
      ]
    },
    "sea-animals": {
      "title": "Морські тварини — Sea Animals",
      "words": [
        { "uk": "риба", "en": "fish" },
        { "uk": "кит", "en": "whale" },
        { "uk": "дельфін", "en": "dolphin" },
        { "uk": "акула", "en": "shark" },
        { "uk": "восьминіг", "en": "octopus" },
        { "uk": "краб", "en": "crab" },
        { "uk": "медуза", "en": "jellyfish" },
        { "uk": "морський коник", "en": "seahorse" },
        { "uk": "тюлень", "en": "seal" },
        { "uk": "креветка", "en": "shrimp" }
      ]
    },
    "music": {
      "title": "Музика — Music",
      "words": [
        { "uk": "музика", "en": "music" },
        { "uk": "пісня", "en": "song" },
        { "uk": "гітара", "en": "guitar" },
        { "uk": "піаніно", "en": "piano" },
        { "uk": "барабан", "en": "drum" },
        { "uk": "скрипка", "en": "violin" },
        { "uk": "флейта", "en": "flute" },
        { "uk": "оркестр", "en": "orchestra" },
        { "uk": "мелодія", "en": "melody" },
        { "uk": "хор", "en": "choir" }
      ]
    },
    "drinks": {
      "title": "Напої — Drinks",
      "words": [
        { "uk": "вода", "en": "water" },
        { "uk": "молоко", "en": "milk" },
        { "uk": "сік", "en": "juice" },
        { "uk": "чай", "en": "tea" },
        { "uk": "какао", "en": "cocoa" },
        { "uk": "компот", "en": "compote" },
        { "uk": "лимонад", "en": "lemonade" },
        { "uk": "кефір", "en": "kefir" },
        { "uk": "йогурт", "en": "yogurt" },
        { "uk": "смузі", "en": "smoothie" }
      ]
    },
    "face": {
      "title": "Обличчя — Face",
      "words": [
        { "uk": "око", "en": "eye" },
        { "uk": "ніс", "en": "nose" },
        { "uk": "рот", "en": "mouth" },
        { "uk": "вухо", "en": "ear" },
        { "uk": "зуб", "en": "tooth" },
        { "uk": "язик", "en": "tongue" },
        { "uk": "губа", "en": "lip" },
        { "uk": "брова", "en": "eyebrow" },
        { "uk": "щока", "en": "cheek" },
        { "uk": "лоб", "en": "forehead" },
        { "uk": "підборіддя", "en": "chin" },
        { "uk": "вія", "en": "eyelash" }
      ]
    },
    "vegetables": {
      "title": "Овочі — Vegetables",
      "words": [
        { "uk": "морква", "en": "carrot" },
        { "uk": "картопля", "en": "potato" },
        { "uk": "помідор", "en": "tomato" },
        { "uk": "огірок", "en": "cucumber" },
        { "uk": "капуста", "en": "cabbage" },
        { "uk": "цибуля", "en": "onion" },
        { "uk": "часник", "en": "garlic" },
        { "uk": "перець", "en": "pepper" },
        { "uk": "буряк", "en": "beet" },
        { "uk": "горох", "en": "peas" },
        { "uk": "кукурудза", "en": "corn" },
        { "uk": "гарбуз", "en": "pumpkin" },
        { "uk": "квасоля", "en": "beans" },
        { "uk": "редиска", "en": "radish" }
      ]
    },
    "clothes": {
      "title": "Одяг — Clothes",
      "words": [
        { "uk": "шапка", "en": "hat" },
        { "uk": "куртка", "en": "jacket" },
        { "uk": "штани", "en": "pants" },
        { "uk": "сукня", "en": "dress" },
        { "uk": "черевики", "en": "boots" },
        { "uk": "шкарпетки", "en": "socks" },
        { "uk": "рукавиці", "en": "gloves" },
        { "uk": "шарф", "en": "scarf" },
        { "uk": "футболка", "en": "t-shirt" },
        { "uk": "спідниця", "en": "skirt" },
        { "uk": "светр", "en": "sweater" },
        { "uk": "пальто", "en": "coat" },
        { "uk": "краватка", "en": "tie" },
        { "uk": "ремінь", "en": "belt" },
        { "uk": "кишеня", "en": "pocket" },
        { "uk": "взуття", "en": "shoes" }
      ]
    },
    "description": {
      "title": "Опис — Description",
      "words": [
        { "uk": "великий", "en": "big" },
        { "uk": "малий", "en": "small" },
        { "uk": "добрий", "en": "good" },
        { "uk": "поганий", "en": "bad" },
        { "uk": "гарний", "en": "beautiful" },
        { "uk": "новий", "en": "new" },
        { "uk": "старий", "en": "old" },
        { "uk": "швидкий", "en": "fast" },
        { "uk": "повільний", "en": "slow" },
        { "uk": "гарячий", "en": "hot" },
        { "uk": "холодний", "en": "cold" },
        { "uk": "довгий", "en": "long" },
        { "uk": "короткий", "en": "short" },
        { "uk": "тихий", "en": "quiet" },
        { "uk": "гучний", "en": "loud" },
        { "uk": "м'який", "en": "soft" },
        { "uk": "твердий", "en": "hard" },
        { "uk": "мокрий", "en": "wet" },
        { "uk": "сухий", "en": "dry" },
        { "uk": "чистий", "en": "clean" },
        { "uk": "брудний", "en": "dirty" },
        { "uk": "легкий", "en": "light" },
        { "uk": "важкий", "en": "heavy" },
        { "uk": "товстий", "en": "thick" },
        { "uk": "тонкий", "en": "thin" },
        { "uk": "широкий", "en": "wide" },
        { "uk": "вузький", "en": "narrow" },
        { "uk": "сильний", "en": "strong" },
        { "uk": "слабкий", "en": "weak" },
        { "uk": "розумний", "en": "smart" },
        { "uk": "дружній", "en": "friendly" },
        { "uk": "особливий", "en": "special" },
        { "uk": "солодкий", "en": "sweet" },
        { "uk": "зроблено", "en": "done" },
        { "uk": "спокійний", "en": "peaceful" },
        { "uk": "приємний", "en": "enjoyable" },
        { "uk": "комфортний", "en": "comfortable" },
        { "uk": "захопливий", "en": "exciting" },
        { "uk": "сонячний", "en": "sunny" },
        { "uk": "цікавий", "en": "interesting" },
        { "uk": "дивовижний", "en": "amazing" },
        { "uk": "чудовий", "en": "wonderful" },
        { "uk": "теплий", "en": "warm" },
        { "uk": "безпечний", "en": "safe" },
        { "uk": "веселий", "en": "fun" }
      ]
    },
    "questions": {
      "title": "Питальні слова — Questions",
      "words": [
        { "uk": "хто", "en": "who" },
        { "uk": "що", "en": "what" },
        { "uk": "де", "en": "where" },
        { "uk": "коли", "en": "when" },
        { "uk": "чому", "en": "why" },
        { "uk": "як", "en": "how" },
        { "uk": "скільки", "en": "how many" },
        { "uk": "який", "en": "which" },
        { "uk": "чий", "en": "whose" },
        { "uk": "що це?", "en": "what's" }
      ]
    },
    "travel": {
      "title": "Подорож — Travel",
      "words": [
        { "uk": "подорож", "en": "journey" },
        { "uk": "пункт призначення", "en": "destination" },
        { "uk": "відправлення", "en": "departure" },
        { "uk": "прибуття", "en": "arrival" },
        { "uk": "бронювання", "en": "reservation" },
        { "uk": "пригода", "en": "adventure" },
        { "uk": "маршрут", "en": "route" },
        { "uk": "житло", "en": "accommodation" },
        { "uk": "екскурсія", "en": "excursion" },
        { "uk": "визначне місце", "en": "landmark" },
        { "uk": "туристична пам'ятка", "en": "attraction" },
        { "uk": "затримка", "en": "delay" },
        { "uk": "вихід на посадку", "en": "departure gate" },
        { "uk": "митниця", "en": "customs" },
        { "uk": "зона видачі багажу", "en": "baggage claim" },
        { "uk": "мандрівник із рюкзаком", "en": "backpacker" },
        { "uk": "туристичне страхування", "en": "travel insurance" }
      ]
    },
    "weather": {
      "title": "Погода — Weather",
      "words": [
        { "uk": "хмара", "en": "cloud" },
        { "uk": "дощ", "en": "rain" },
        { "uk": "сніг", "en": "snow" },
        { "uk": "вітер", "en": "wind" },
        { "uk": "грім", "en": "thunder" },
        { "uk": "блискавка", "en": "lightning" },
        { "uk": "веселка", "en": "rainbow" },
        { "uk": "туман", "en": "fog" },
        { "uk": "мороз", "en": "frost" },
        { "uk": "спека", "en": "heat" },
        { "uk": "град", "en": "hail" },
        { "uk": "калюжа", "en": "puddle" },
        { "uk": "погода", "en": "weather" },
        { "uk": "тіні", "en": "shadows" }
      ]
    },
    "position": {
      "title": "Позиція — Position",
      "words": [
        { "uk": "тут", "en": "here" },
        { "uk": "там", "en": "there" },
        { "uk": "далеко", "en": "far" },
        { "uk": "близько", "en": "near" },
        { "uk": "всередині", "en": "inside" },
        { "uk": "зовні", "en": "outside" },
        { "uk": "під", "en": "under" },
        { "uk": "над", "en": "above" },
        { "uk": "за", "en": "behind" },
        { "uk": "перед", "en": "in front" },
        { "uk": "між", "en": "between" },
        { "uk": "поруч", "en": "next to" },
        { "uk": "ліворуч", "en": "left" },
        { "uk": "праворуч", "en": "right" },
        { "uk": "вгору", "en": "up" },
        { "uk": "вниз", "en": "down" }
      ]
    },
    "seasons": {
      "title": "Пори року — Seasons",
      "words": [
        { "uk": "зима", "en": "winter" },
        { "uk": "весна", "en": "spring" },
        { "uk": "літо", "en": "summer" },
        { "uk": "осінь", "en": "autumn" }
      ]
    },
    "everyday-objects": {
      "title": "Предмети — Everyday Objects",
      "words": [
        { "uk": "ключ", "en": "key" },
        { "uk": "телефон", "en": "phone" },
        { "uk": "комп'ютер", "en": "computer" },
        { "uk": "парасолька", "en": "umbrella" },
        { "uk": "сумка", "en": "bag" },
        { "uk": "окуляри", "en": "glasses" },
        { "uk": "фотоапарат", "en": "camera" },
        { "uk": "вікно", "en": "window" },
        { "uk": "двері", "en": "door" },
        { "uk": "свічка", "en": "candle" },
        { "uk": "коробка", "en": "box" },
        { "uk": "пакет", "en": "bag" },
        { "uk": "батарейка", "en": "battery" },
        { "uk": "мотузка", "en": "rope" },
        { "uk": "замок", "en": "lock" },
        { "uk": "годинник", "en": "watch" },
        { "uk": "знаки", "en": "signs" }
      ]
    },
    "greetings": {
      "title": "Привітання — Greetings",
      "words": [
        { "uk": "так", "en": "yes" },
        { "uk": "ні", "en": "no" },
        { "uk": "привіт", "en": "hello" },
        { "uk": "бувай", "en": "bye" },
        { "uk": "дякую", "en": "thank you" },
        { "uk": "будь ласка", "en": "please" },
        { "uk": "вибачте", "en": "sorry" },
        { "uk": "добрий ранок", "en": "good morning" },
        { "uk": "добрий вечір", "en": "good evening" },
        { "uk": "на добраніч", "en": "good night" },
        { "uk": "як справи", "en": "how are you" },
        { "uk": "до побачення", "en": "goodbye" }
      ]
    },
    "prepositions": {
      "title": "Прийменники — Prepositions",
      "words": [
        { "uk": "незважаючи на", "en": "despite" },
        { "uk": "у напрямку до", "en": "towards" },
        { "uk": "за межами", "en": "beyond" },
        { "uk": "під (нижче)", "en": "beneath" },
        { "uk": "серед", "en": "among" },
        { "uk": "в межах", "en": "within" },
        { "uk": "поза, за межами", "en": "outside" },
        { "uk": "всередині", "en": "inside" },
        { "uk": "навпроти", "en": "opposite" },
        { "uk": "щодо", "en": "regarding" },
        { "uk": "стосовно", "en": "concerning" },
        { "uk": "поруч із", "en": "alongside" },
        { "uk": "проти", "en": "against" },
        { "uk": "повз", "en": "past" },
        { "uk": "через, за допомогою", "en": "via" },
        { "uk": "крім", "en": "except" },
        { "uk": "на відміну від", "en": "unlike" },
        { "uk": "включаючи", "en": "including" },
        { "uk": "виключаючи", "en": "excluding" }
      ]
    },
    "nature": {
      "title": "Природа — Nature",
      "words": [
        { "uk": "сонце", "en": "sun" },
        { "uk": "місяць", "en": "moon" },
        { "uk": "зірка", "en": "star" },
        { "uk": "небо", "en": "sky" },
        { "uk": "дерево", "en": "tree" },
        { "uk": "квітка", "en": "flower" },
        { "uk": "трава", "en": "grass" },
        { "uk": "ліс", "en": "forest" },
        { "uk": "гора", "en": "mountain" },
        { "uk": "річка", "en": "river" },
        { "uk": "море", "en": "sea" },
        { "uk": "озеро", "en": "lake" },
        { "uk": "поле", "en": "field" },
        { "uk": "сад", "en": "garden" },
        { "uk": "острів", "en": "island" },
        { "uk": "земля", "en": "earth" },
        { "uk": "камінь", "en": "stone" },
        { "uk": "пісок", "en": "sand" },
        { "uk": "болото", "en": "swamp" },
        { "uk": "печера", "en": "cave" },
        { "uk": "повітря", "en": "air" },
        { "uk": "ґрунт", "en": "soil" }
      ]
    },
    "adverbs": {
      "title": "Прислівники — Adverbs",
      "words": [
        { "uk": "значно, суттєво", "en": "significantly" },
        { "uk": "по суті, фактично", "en": "essentially" },
        { "uk": "відносно, порівняно", "en": "relatively" },
        { "uk": "широко, ґрунтовно", "en": "extensively" },
        { "uk": "отже, унаслідок цього", "en": "consequently" },
        { "uk": "зрештою, у кінцевому підсумку", "en": "ultimately" },
        { "uk": "імовірно, мабуть", "en": "presumably" },
        { "uk": "широко", "en": "widely" },
        { "uk": "дуже, надзвичайно", "en": "highly" },
        { "uk": "практично, фактично", "en": "virtually" },
        { "uk": "конкретно, зокрема", "en": "specifically" },
        { "uk": "відповідно", "en": "accordingly" },
        { "uk": "дедалі більше", "en": "increasingly" },
        { "uk": "неминуче", "en": "inevitably" },
        { "uk": "напрочуд, надзвичайно", "en": "remarkably" },
        { "uk": "істотно, значною мірою", "en": "substantially" },
        { "uk": "теоретично", "en": "theoretically" },
        { "uk": "очевидно, мабуть", "en": "apparently" },
        { "uk": "особливо, помітно", "en": "notably" },
        { "uk": "тим не менш", "en": "nevertheless" },
        { "uk": "згодом", "en": "subsequently" },
        { "uk": "ледве", "en": "barely" },
        { "uk": "загалом", "en": "broadly" },
        { "uk": "нібито", "en": "allegedly" },
        { "uk": "точно", "en": "precisely" },
        { "uk": "ретельно", "en": "thoroughly" },
        { "uk": "одночасно", "en": "simultaneously" },
        { "uk": "поступово", "en": "gradually" },
        { "uk": "приблизно", "en": "roughly" },
        { "uk": "безсумнівно", "en": "undoubtedly" },
        { "uk": "неохоче", "en": "reluctantly" },
        { "uk": "послідовно", "en": "consistently" },
        { "uk": "насправді", "en": "actually" },
        { "uk": "ймовірно", "en": "probably" },
        { "uk": "нещодавно", "en": "recently" },
        { "uk": "на щастя", "en": "fortunately" },
        { "uk": "на жаль", "en": "unfortunately" },
        { "uk": "очевидно", "en": "obviously" },
        { "uk": "раптово", "en": "suddenly" },
        { "uk": "чітко, ясно", "en": "clearly" },
        { "uk": "серйозно", "en": "seriously" },
        { "uk": "чесно кажучи", "en": "honestly" },
        { "uk": "точно, саме так", "en": "exactly" },
        { "uk": "особливо", "en": "especially" },
        { "uk": "повністю", "en": "completely" },
        { "uk": "обережно", "en": "carefully" },
        { "uk": "природно", "en": "naturally" },
        { "uk": "безумовно", "en": "definitely" },
        { "uk": "дивовижно", "en": "surprisingly" },
        { "uk": "ввічливо", "en": "politely" },
        { "uk": "негайно", "en": "immediately" },
        { "uk": "точно", "en": "accurately" },
        { "uk": "приблизно", "en": "approximately" },
        { "uk": "безумовно, звичайно", "en": "certainly" },
        { "uk": "навмисно, свідомо", "en": "deliberately" },
        { "uk": "спочатку, спершу", "en": "initially" },
        { "uk": "обов'язково", "en": "necessarily" }
      ]
    },
    "frequency-adverbs": {
      "title": "Прислівники частоти — Frequency Adverbs",
      "words": [
        { "uk": "завжди", "en": "always" },
        { "uk": "зазвичай", "en": "usually" },
        { "uk": "часто", "en": "frequently" },
        { "uk": "часто", "en": "often" },
        { "uk": "іноді", "en": "sometimes" },
        { "uk": "час від часу", "en": "occasionally" },
        { "uk": "рідко", "en": "rarely" },
        { "uk": "зрідка", "en": "seldom" },
        { "uk": "ніколи", "en": "never" }
      ]
    },
    "professions": {
      "title": "Професії — Professions",
      "words": [
        { "uk": "лікар", "en": "doctor" },
        { "uk": "пожежник", "en": "firefighter" },
        { "uk": "поліцейський", "en": "police officer" },
        { "uk": "кухар", "en": "cook" },
        { "uk": "водій", "en": "driver" },
        { "uk": "фермер", "en": "farmer" },
        { "uk": "пілот", "en": "pilot" },
        { "uk": "будівельник", "en": "builder" },
        { "uk": "художник", "en": "artist" },
        { "uk": "музикант", "en": "musician" },
        { "uk": "продавець", "en": "seller" },
        { "uk": "перукар", "en": "hairdresser" },
        { "uk": "космонавт", "en": "astronaut" },
        { "uk": "ветеринар", "en": "vet" },
        { "uk": "пекар", "en": "baker" },
        { "uk": "медсестра", "en": "nurse" },
        { "uk": "танцівник", "en": "dancer" },
        { "uk": "актор", "en": "actor" },
        { "uk": "робота", "en": "job" }
      ]
    },
    "birds": {
      "title": "Птахи — Birds",
      "words": [
        { "uk": "птах", "en": "bird" },
        { "uk": "горобець", "en": "sparrow" },
        { "uk": "ворона", "en": "crow" },
        { "uk": "голуб", "en": "pigeon" },
        { "uk": "орел", "en": "eagle" },
        { "uk": "сова", "en": "owl" },
        { "uk": "лелека", "en": "stork" },
        { "uk": "ластівка", "en": "swallow" },
        { "uk": "синиця", "en": "tit" },
        { "uk": "дятел", "en": "woodpecker" },
        { "uk": "пінгвін", "en": "penguin" },
        { "uk": "фламінго", "en": "flamingo" }
      ]
    },
    "plants": {
      "title": "Рослини — Plants",
      "words": [
        { "uk": "троянда", "en": "rose" },
        { "uk": "тюльпан", "en": "tulip" },
        { "uk": "соняшник", "en": "sunflower" },
        { "uk": "ромашка", "en": "daisy" },
        { "uk": "кущ", "en": "bush" },
        { "uk": "листок", "en": "leaf" },
        { "uk": "корінь", "en": "root" },
        { "uk": "гілка", "en": "branch" },
        { "uk": "насіння", "en": "seed" },
        { "uk": "гриб", "en": "mushroom" },
        { "uk": "кактус", "en": "cactus" },
        { "uk": "лілія", "en": "lily" },
        { "uk": "рослина", "en": "plant" }
      ]
    },
    "flowers": {
      "title": "Квіти — Flowers",
      "words": [
        { "uk": "квіт сакури", "en": "cherry blossom" },
        { "uk": "гібіскус", "en": "hibiscus" },
        { "uk": "нарцис", "en": "daffodil" },
        { "uk": "лаванда", "en": "lavender" },
        { "uk": "півонія", "en": "peony" },
        { "uk": "орхідея", "en": "orchid" },
        { "uk": "хризантема", "en": "chrysanthemum" },
        { "uk": "гвоздика", "en": "carnation" },
        { "uk": "чорнобривці", "en": "marigold" },
        { "uk": "жасмин", "en": "jasmine" },
        { "uk": "магнолія", "en": "magnolia" },
        { "uk": "мак", "en": "poppy" },
        { "uk": "ірис", "en": "iris" },
        { "uk": "фіалка", "en": "violet" },
        { "uk": "гортензія", "en": "hydrangea" }
      ]
    },
    "world": {
      "title": "Світ — World",
      "words": [
        { "uk": "країна", "en": "country" },
        { "uk": "прапор", "en": "flag" },
        { "uk": "карта", "en": "map" },
        { "uk": "океан", "en": "ocean" },
        { "uk": "континент", "en": "continent" },
        { "uk": "пустеля", "en": "desert" },
        { "uk": "джунглі", "en": "jungle" },
        { "uk": "північ", "en": "north" },
        { "uk": "південь", "en": "south" },
        { "uk": "схід", "en": "east" },
        { "uk": "захід", "en": "west" },
        { "uk": "столиця", "en": "capital" },
        { "uk": "ферма", "en": "farm" }
      ]
    },
    "holidays": {
      "title": "Свята — Holidays",
      "words": [
        { "uk": "день народження", "en": "birthday" },
        { "uk": "Новий рік", "en": "New Year" },
        { "uk": "Різдво", "en": "Christmas" },
        { "uk": "Великдень", "en": "Easter" },
        { "uk": "свято", "en": "holiday" },
        { "uk": "подарунок", "en": "gift" },
        { "uk": "листівка", "en": "card" },
        { "uk": "ялинка", "en": "Christmas tree" },
        { "uk": "феєрверк", "en": "fireworks" },
        { "uk": "гірлянда", "en": "garland" }
      ]
    },
    "family": {
      "title": "Сім'я — Family",
      "words": [
        { "uk": "мама", "en": "mom" },
        { "uk": "тато", "en": "dad" },
        { "uk": "брат", "en": "brother" },
        { "uk": "сестра", "en": "sister" },
        { "uk": "бабуся", "en": "grandma" },
        { "uk": "дідусь", "en": "grandpa" },
        { "uk": "дитина", "en": "baby" },
        { "uk": "син", "en": "son" },
        { "uk": "дочка", "en": "daughter" },
        { "uk": "родина", "en": "family" },
        { "uk": "тітка", "en": "aunt" },
        { "uk": "дядько", "en": "uncle" }
      ]
    },
    "function-words": {
      "title": "Службові слова — Function Words",
      "words": [
        { "uk": "про", "en": "about" },
        { "uk": "після", "en": "after" },
        { "uk": "знову", "en": "again" },
        { "uk": "і", "en": "and" },
        { "uk": "для", "en": "for" },
        { "uk": "в", "en": "in" },
        { "uk": "не", "en": "not" },
        { "uk": "зараз", "en": "now" },
        { "uk": "на", "en": "on" },
        { "uk": "або", "en": "or" },
        { "uk": "потім", "en": "then" },
        { "uk": "з", "en": "with" },
        { "uk": "багато", "en": "many" },
        { "uk": "скрізь", "en": "everywhere" },
        { "uk": "разом", "en": "together" },
        { "uk": "добре", "en": "well" },
        { "uk": "різниця", "en": "difference" }
      ]
    },
    "sweets": {
      "title": "Солодощі — Sweets",
      "words": [
        { "uk": "торт", "en": "cake" },
        { "uk": "цукерка", "en": "candy" },
        { "uk": "печиво", "en": "cookie" },
        { "uk": "шоколад", "en": "chocolate" },
        { "uk": "морозиво", "en": "ice cream" },
        { "uk": "мед", "en": "honey" },
        { "uk": "цукор", "en": "sugar" },
        { "uk": "варення", "en": "jam" },
        { "uk": "пиріг", "en": "pie" },
        { "uk": "тістечко", "en": "pastry" }
      ]
    },
    "conjunctions": {
      "title": "Сполучники — Conjunctions",
      "words": [
        { "uk": "тому що", "en": "because" },
        { "uk": "тому, отже", "en": "so" },
        { "uk": "якщо", "en": "if" },
        { "uk": "коли", "en": "when" },
        { "uk": "поки, тоді як", "en": "while" },
        { "uk": "перед тим як", "en": "before" },
        { "uk": "після того як", "en": "after" },
        { "uk": "хоча", "en": "although" },
        { "uk": "оскільки", "en": "since" },
        { "uk": "якщо не", "en": "unless" },
        { "uk": "доки не", "en": "until" },
        { "uk": "оскільки, коли", "en": "as" },
        { "uk": "ніж", "en": "than" },
        { "uk": "де", "en": "where" },
        { "uk": "чи", "en": "whether" },
        { "uk": "щойно, як тільки", "en": "once" },
        { "uk": "хоча, незважаючи на те що", "en": "even though" },
        { "uk": "як тільки", "en": "as soon as" },
        { "uk": "на випадок якщо", "en": "in case" },
        { "uk": "для того щоб", "en": "so that" }
      ]
    },
    "sports": {
      "title": "Спорт — Sports",
      "words": [
        { "uk": "футбол", "en": "football" },
        { "uk": "баскетбол", "en": "basketball" },
        { "uk": "плавання", "en": "swimming" },
        { "uk": "біг", "en": "running" },
        { "uk": "гімнастика", "en": "gymnastics" },
        { "uk": "теніс", "en": "tennis" },
        { "uk": "хокей", "en": "hockey" },
        { "uk": "волейбол", "en": "volleyball" },
        { "uk": "танці", "en": "dancing" },
        { "uk": "карате", "en": "karate" },
        { "uk": "ковзани", "en": "skating" },
        { "uk": "лижі", "en": "skiing" }
      ]
    },
    "idioms": {
      "title": "Сталі вирази — Set Expressions",
      "words": [
        { "uk": "прийняти рішення", "en": "to make up one's mind" },
        { "uk": "відповідати за щось / бути керівником", "en": "to be in charge of" },
        { "uk": "брати до уваги", "en": "to take into account" },
        { "uk": "випадково натрапити", "en": "to come across" },
        { "uk": "закінчитися (про щось)", "en": "to run out of" },
        { "uk": "добре ладнати з кимось", "en": "to get along with" },
        { "uk": "звісно, безумовно", "en": "by all means" },
        { "uk": "у довгостроковій перспективі", "en": "in the long run" },
        { "uk": "зрештою, в кінцевому підсумку", "en": "at the end of the day" },
        { "uk": "наразі, поки що", "en": "for the time being" },
        { "uk": "загалом", "en": "on the whole" },
        { "uk": "по-перше; насамперед", "en": "in the first place" },
        { "uk": "аж ніяк, ні в якому разі", "en": "by no means" },
        { "uk": "тим часом", "en": "in the meantime" },
        { "uk": "певною мірою", "en": "to some extent" },
        { "uk": "фактично, насправді", "en": "as a matter of fact" },
        { "uk": "вирішувати тобі", "en": "it's up to you" },
        { "uk": "нічого не можу з цим вдіяти", "en": "I can't help it" },
        { "uk": "не поспішай", "en": "take your time" },
        { "uk": "саме в цьому суть", "en": "that's the point" },
        { "uk": "це не має значення", "en": "it doesn't matter" },
        { "uk": "наскільки я знаю", "en": "as far as I know" },
        { "uk": "до речі", "en": "by the way" },
        { "uk": "не дивно", "en": "no wonder" },
        { "uk": "чомусь", "en": "for some reason" },
        { "uk": "принаймні", "en": "at least" },
        { "uk": "сприймати як належне", "en": "take something for granted" },
        { "uk": "бути під тиском", "en": "be under pressure" },
        { "uk": "докладати особливих зусиль", "en": "go out of your way" },
        { "uk": "відігравати ключову роль", "en": "play a key role" },
        { "uk": "підвищувати обізнаність", "en": "raise awareness" },
        { "uk": "зіткнутися з наслідками", "en": "face the consequences" },
        { "uk": "справляти незабутнє враження", "en": "make a lasting impression" },
        { "uk": "іти на великі зусилля", "en": "go to great lengths" },
        { "uk": "служити певній меті", "en": "serve a purpose" },
        { "uk": "знаходити баланс", "en": "strike a balance" }
      ]
    },
    "state": {
      "title": "Стан — State",
      "words": [
        { "uk": "хворий", "en": "sick" },
        { "uk": "здоровий", "en": "healthy" },
        { "uk": "голодний", "en": "hungry" },
        { "uk": "ситий", "en": "full" },
        { "uk": "втомлений", "en": "tired" },
        { "uk": "бадьорий", "en": "energetic" },
        { "uk": "веселий", "en": "cheerful" },
        { "uk": "сумний", "en": "sad" },
        { "uk": "сердитий", "en": "angry" },
        { "uk": "щасливий", "en": "happy" },
        { "uk": "зайнятий", "en": "busy" },
        { "uk": "вільний", "en": "free" }
      ]
    },
    "pets": {
      "title": "Домашні тварини — Pets",
      "words": [
        { "uk": "кіт", "en": "cat" },
        { "uk": "пес", "en": "dog" },
        { "uk": "хом'як", "en": "hamster" },
        { "uk": "папуга", "en": "parrot" },
        { "uk": "кролик", "en": "rabbit" },
        { "uk": "рибка", "en": "goldfish" },
        { "uk": "черепаха", "en": "turtle" },
        { "uk": "канарка", "en": "canary" },
        { "uk": "домашня тварина", "en": "pet" }
      ]
    },
    "wild-animals": {
      "title": "Дикі тварини — Wild Animals",
      "words": [
        { "uk": "ведмідь", "en": "bear" },
        { "uk": "заєць", "en": "hare" },
        { "uk": "лисиця", "en": "fox" },
        { "uk": "вовк", "en": "wolf" },
        { "uk": "олень", "en": "deer" },
        { "uk": "білка", "en": "squirrel" },
        { "uk": "їжак", "en": "hedgehog" },
        { "uk": "лев", "en": "lion" },
        { "uk": "тигр", "en": "tiger" },
        { "uk": "слон", "en": "elephant" },
        { "uk": "жирафа", "en": "giraffe" },
        { "uk": "мавпа", "en": "monkey" },
        { "uk": "зебра", "en": "zebra" },
        { "uk": "крокодил", "en": "crocodile" },
        { "uk": "бегемот", "en": "hippo" },
        { "uk": "носоріг", "en": "rhino" },
        { "uk": "панда", "en": "panda" },
        { "uk": "кенгуру", "en": "kangaroo" },
        { "uk": "тварина", "en": "animal" },
        { "uk": "ігуана", "en": "iguana" }
      ]
    },
    "body": {
      "title": "Тіло — Body",
      "words": [
        { "uk": "рука", "en": "hand" },
        { "uk": "нога", "en": "leg" },
        { "uk": "голова", "en": "head" },
        { "uk": "серце", "en": "heart" },
        { "uk": "палець", "en": "finger" },
        { "uk": "коліно", "en": "knee" },
        { "uk": "спина", "en": "back" },
        { "uk": "живіт", "en": "tummy" },
        { "uk": "шия", "en": "neck" },
        { "uk": "плече", "en": "shoulder" },
        { "uk": "лікоть", "en": "elbow" },
        { "uk": "стопа", "en": "foot" },
        { "uk": "волосся", "en": "hair" },
        { "uk": "шкіра", "en": "skin" },
        { "uk": "кістка", "en": "bone" },
        { "uk": "кров", "en": "blood" },
        { "uk": "хвіст", "en": "tail" }
      ]
    },
    "transport": {
      "title": "Транспорт — Transport",
      "words": [
        { "uk": "машина", "en": "car" },
        { "uk": "автобус", "en": "bus" },
        { "uk": "літак", "en": "plane" },
        { "uk": "потяг", "en": "train" },
        { "uk": "велосипед", "en": "bike" },
        { "uk": "корабель", "en": "ship" },
        { "uk": "метро", "en": "metro" },
        { "uk": "таксі", "en": "taxi" },
        { "uk": "мотоцикл", "en": "motorcycle" },
        { "uk": "вертоліт", "en": "helicopter" },
        { "uk": "трамвай", "en": "tram" },
        { "uk": "човен", "en": "boat" },
        { "uk": "ракета", "en": "rocket" },
        { "uk": "вантажівка", "en": "truck" },
        { "uk": "самокат", "en": "scooter" },
        { "uk": "карета", "en": "carriage" }
      ]
    },
    "farm-animals": {
      "title": "Тварини ферми — Farm Animals",
      "words": [
        { "uk": "корова", "en": "cow" },
        { "uk": "кінь", "en": "horse" },
        { "uk": "курка", "en": "chicken" },
        { "uk": "свиня", "en": "pig" },
        { "uk": "вівця", "en": "sheep" },
        { "uk": "коза", "en": "goat" },
        { "uk": "качка", "en": "duck" },
        { "uk": "гуска", "en": "goose" },
        { "uk": "індик", "en": "turkey" },
        { "uk": "осел", "en": "donkey" },
        { "uk": "півень", "en": "rooster" },
        { "uk": "кролик", "en": "rabbit" }
      ]
    },
    "shapes": {
      "title": "Форми — Shapes",
      "words": [
        { "uk": "коло", "en": "circle" },
        { "uk": "квадрат", "en": "square" },
        { "uk": "трикутник", "en": "triangle" },
        { "uk": "прямокутник", "en": "rectangle" },
        { "uk": "овал", "en": "oval" },
        { "uk": "ромб", "en": "diamond" },
        { "uk": "куб", "en": "cube" },
        { "uk": "куля", "en": "sphere" }
      ]
    },
    "phrasal-verbs": {
      "title": "Фразові дієслова — Phrasal Verbs",
      "words": [
        { "uk": "прокидатися", "en": "wake up" },
        { "uk": "вставати", "en": "get up" },
        { "uk": "вмикати", "en": "turn on" },
        { "uk": "вимикати", "en": "turn off" },
        { "uk": "шукати", "en": "look for" },
        { "uk": "дізнаватися", "en": "find out" },
        { "uk": "одягати", "en": "put on" },
        { "uk": "знімати", "en": "take off" },
        { "uk": "підбирати, забирати", "en": "pick up" },
        { "uk": "сідати", "en": "sit down" },
        { "uk": "вставати", "en": "stand up" },
        { "uk": "повертатися", "en": "come back" },
        { "uk": "виходити", "en": "go out" },
        { "uk": "виростати", "en": "grow up" },
        { "uk": "повертати", "en": "give back" },
        { "uk": "приміряти", "en": "try on" },
        { "uk": "доглядати", "en": "look after" },
        { "uk": "передзвонювати", "en": "call back" },
        { "uk": "поспішати", "en": "hurry up" }
      ]
    },
    "fruits": {
      "title": "Фрукти — Fruits",
      "words": [
        { "uk": "яблуко", "en": "apple" },
        { "uk": "банан", "en": "banana" },
        { "uk": "апельсин", "en": "orange" },
        { "uk": "полуниця", "en": "strawberry" },
        { "uk": "виноград", "en": "grape" },
        { "uk": "кавун", "en": "watermelon" },
        { "uk": "лимон", "en": "lemon" },
        { "uk": "груша", "en": "pear" },
        { "uk": "вишня", "en": "cherry" },
        { "uk": "персик", "en": "peach" },
        { "uk": "ківі", "en": "kiwi" },
        { "uk": "ананас", "en": "pineapple" },
        { "uk": "слива", "en": "plum" },
        { "uk": "малина", "en": "raspberry" }
      ]
    },
    "time": {
      "title": "Час — Time",
      "words": [
        { "uk": "час", "en": "time" },
        { "uk": "година", "en": "hour" },
        { "uk": "хвилина", "en": "minute" },
        { "uk": "секунда", "en": "second" },
        { "uk": "тиждень", "en": "week" },
        { "uk": "місяць", "en": "month" },
        { "uk": "рік", "en": "year" },
        { "uk": "сьогодні", "en": "today" },
        { "uk": "вчора", "en": "yesterday" },
        { "uk": "завтра", "en": "tomorrow" },
        { "uk": "день", "en": "day" }
      ]
    },
    "time-of-day": {
      "title": "Час доби — Time of Day",
      "words": [
        { "uk": "ранок", "en": "morning" },
        { "uk": "день", "en": "afternoon" },
        { "uk": "вечір", "en": "evening" },
        { "uk": "ніч", "en": "night" },
        { "uk": "світанок", "en": "dawn" },
        { "uk": "захід", "en": "sunset" }
      ]
    },
    "time-adverbs": {
      "title": "Прислівники часу — Time Adverbs",
      "words": [
        { "uk": "скоро", "en": "soon" },
        { "uk": "рано", "en": "early" },
        { "uk": "пізно", "en": "late" },
        { "uk": "вже", "en": "already" },
        { "uk": "досі, ще", "en": "still" },
        { "uk": "нарешті", "en": "finally" },
        { "uk": "зрештою", "en": "eventually" },
        { "uk": "тим часом", "en": "meanwhile" },
        { "uk": "потім, згодом", "en": "afterwards" },
        { "uk": "нині, у наш час", "en": "nowadays" }
      ]
    },
    "numbers": {
      "title": "Числа — Numbers",
      "words": [
        { "uk": "нуль", "en": "zero" },
        { "uk": "один", "en": "one" },
        { "uk": "два", "en": "two" },
        { "uk": "три", "en": "three" },
        { "uk": "чотири", "en": "four" },
        { "uk": "п'ять", "en": "five" },
        { "uk": "шість", "en": "six" },
        { "uk": "сім", "en": "seven" },
        { "uk": "вісім", "en": "eight" },
        { "uk": "дев'ять", "en": "nine" },
        { "uk": "десять", "en": "ten" },
        { "uk": "одинадцять", "en": "eleven" },
        { "uk": "дванадцять", "en": "twelve" },
        { "uk": "двадцять", "en": "twenty" },
        { "uk": "тридцять", "en": "thirty" },
        { "uk": "сорок", "en": "forty" },
        { "uk": "п'ятдесят", "en": "fifty" },
        { "uk": "сто", "en": "hundred" },
        { "uk": "тисяча", "en": "thousand" },
        { "uk": "мільйон", "en": "million" },
        { "uk": "число; номер", "en": "number" }
      ]
    },
    "school": {
      "title": "Школа — School",
      "words": [
        { "uk": "школа", "en": "school" },
        { "uk": "книга", "en": "book" },
        { "uk": "ручка", "en": "pen" },
        { "uk": "олівець", "en": "pencil" },
        { "uk": "зошит", "en": "notebook" },
        { "uk": "рюкзак", "en": "backpack" },
        { "uk": "клас", "en": "classroom" },
        { "uk": "дошка", "en": "board" },
        { "uk": "крейда", "en": "chalk" },
        { "uk": "лінійка", "en": "ruler" },
        { "uk": "гумка", "en": "eraser" },
        { "uk": "підручник", "en": "textbook" },
        { "uk": "урок", "en": "lesson" },
        { "uk": "вчитель", "en": "teacher" },
        { "uk": "учень", "en": "student" },
        { "uk": "перерва", "en": "break" },
        { "uk": "літера", "en": "letter" },
        { "uk": "слово", "en": "word" },
        { "uk": "картинка", "en": "picture" }
      ]
    }
  }
};
